module controller(
	sys_clk_i,
	sys_rst_n_i,
	motor_spin_dir_i,
	motor_rpm_set_i,
	motor_acc_set_i,
	motor_rpm_max_i,
	Speed_PID_parameter_P,
	Speed_PID_parameter_I,
	Speed_PID_parameter_D,
	encoder_value_valid_i,
	encoder_direction_i,
	encoder_speed_i,
	encoder_acc_i,
	pwm_duty_o,
	controller_spin_dir_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input motor_spin_dir_i;
	input [15:0] motor_rpm_set_i;
	input [15:0] motor_acc_set_i;
	input [15:0] motor_rpm_max_i;
	input [15:0] Speed_PID_parameter_P;
	input [15:0] Speed_PID_parameter_I;
	input [15:0] Speed_PID_parameter_D;
	input encoder_value_valid_i;
	input encoder_direction_i;
	input [15:0] encoder_speed_i;
	input [15:0] encoder_acc_i;
	output [10:0] pwm_duty_o;
	output controller_spin_dir_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire motor_spin_dir_i;
	wire [15:0] motor_rpm_set_i;
	wire [15:0] motor_acc_set_i;
	wire [15:0] motor_rpm_max_i;
	wire [15:0] Speed_PID_parameter_P;
	wire [15:0] Speed_PID_parameter_I;
	wire [15:0] Speed_PID_parameter_D;
	wire encoder_value_valid_i;
	wire encoder_direction_i;
	wire [15:0] encoder_speed_i;
	wire [15:0] encoder_acc_i;
	reg [10:0] pwm_duty_o;
	reg controller_spin_dir_o;

	//----Code starts here: integrated by Robei-----
	localparam C_MAX_SPEED              = 'd5000; //速度的最大值
	
	localparam S_SPEED_MODE             = 'd0; //速度模式
	//localparam S_SPEED_TO_ANGLE         = 'd1; //速度向角度模式转换
	//localparam S_ANGLE_MODE_WAIT        = 'd2; //切换到等待模式，等待角度使能信号
	//localparam S_ANGLE_MODE             = 'd3; //角度模式
	
	reg[3:0]    state , next_state;
	
	reg[15:0]   expected_value; 
	
	//速度环
	wire        c_speed_loop_en;
	wire        pid_calculate_en;
	wire        c_speed_loop_dir;
	wire[15:0]  c_speed_loop_rmp;
	
	
	//反馈
	wire        pid_feedback_ack;
	wire        pid_feedback_dir;
	wire[15:0]  pid_feedback_value;
	
	assign c_speed_loop_en = ( state == S_SPEED_MODE ) ? 1'b1 : 1'b0;
	
	
	assign pid_calculate_en = ( state == S_SPEED_MODE) ?  encoder_value_valid_i : encoder_value_valid_i;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        state <= S_SPEED_MODE;
	    else
	        state <= S_SPEED_MODE;
	end
	/*
	always@(*) begin
	    case(state)
	    S_SPEED_MODE:
	        if( motor_mode_set_i == 2'b01)
	            next_state <= S_SPEED_TO_ANGLE;
	        else
	            next_state <= S_SPEED_MODE;
	    S_SPEED_TO_ANGLE:
	        if( encoder_speed_i < 'd2 ) //速度降低后，进入角度模式
	            next_state <= S_ANGLE_MODE_WAIT;
	        else
	            next_state <= S_SPEED_TO_ANGLE;
	    S_ANGLE_MODE_WAIT:
	        if( motor_mode_set_i == 2'b00)
	            next_state <= S_SPEED_MODE;
	        else if( motor_angle_en_i == 1'b1)
	            next_state <= S_ANGLE_MODE;
	        else
	            next_state <= S_ANGLE_MODE_WAIT;
	    S_ANGLE_MODE:
	        if( motor_angle_ack_o == 1'b1 )
	            next_state <= S_ANGLE_MODE_WAIT;
	        else
	            next_state <= S_ANGLE_MODE;
	    default : next_state <= S_SPEED_MODE;
	    endcase
	end
	*/
	//期望速度设置
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        expected_value <= 'd0;
	    else if( state == S_SPEED_MODE )
	        expected_value <= c_speed_loop_rmp;
	    else
	        expected_value <= 'd0;
	end
	
	
	
	
	//运动方向切换
	always@( posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0 )
	        controller_spin_dir_o <= motor_spin_dir_i;
	    else if( state == S_SPEED_MODE)
	        controller_spin_dir_o <= c_speed_loop_dir;
	    else
	        controller_spin_dir_o <= controller_spin_dir_o;
	end
	
	//占空比切换
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0 )
	        pwm_duty_o <= 'd0;
	    // else if( encoder_accumulate_clr_o == 1'b1)
	    //    pwm_duty_o <= 'd0;
	    else if( pid_feedback_ack == 1'b1 )
	        if( pid_feedback_dir == 1'b0)
	            if( pwm_duty_o + pid_feedback_value > 'd2047)
	                pwm_duty_o <= 'd2047;
	            else
	                pwm_duty_o <= pwm_duty_o + pid_feedback_value;
	        else if( pwm_duty_o > pid_feedback_value)
	            pwm_duty_o <= pwm_duty_o - pid_feedback_value;
	        else
	            pwm_duty_o <= 'd0;
	    else
	        pwm_duty_o <= pwm_duty_o;
	end
	
	//---Module instantiation---
	controller_Speed_loop controller_Speed_loop1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.c_speed_loop_en_i(c_speed_loop_en),
		.motor_spin_dir_i(motor_spin_dir_i),
		.motor_rpm_set_i(motor_rpm_set_i),
		.encoder_direction_i(encoder_direction_i),
		.encoder_speed_i(encoder_speed_i),
		.c_speed_loop_dir_o(c_speed_loop_dir),
		.c_speed_loop_rmp_o(c_speed_loop_rmp));

	controller_PID #( 'd16, 'd500) controller_PID2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.expected_value_i(expected_value),
		.actual_value_i(encoder_speed_i),
		.pid_calculate_en_i(pid_calculate_en),
		.PID_parameter_P(Speed_PID_parameter_P),
		.PID_parameter_I(Speed_PID_parameter_I),
		.PID_parameter_D(Speed_PID_parameter_D),
		.pid_feedback_ack_o(pid_feedback_ack),
		.pid_feedback_dir_o(pid_feedback_dir),
		.pid_feedback_value_o(pid_feedback_value));

endmodule    //controller

