module controller_PID(
	sys_clk_i,
	sys_rst_n_i,
	expected_value_i,
	actual_value_i,
	pid_calculate_en_i,
	PID_parameter_P,
	PID_parameter_I,
	PID_parameter_D,
	pid_feedback_ack_o,
	pid_feedback_dir_o,
	pid_feedback_value_o);

	//----Parameters:: generated by Robei-----
	parameter DATA_WIDTH = 'd16;
	parameter P_FB_MAX     = 'd500;

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [DATA_WIDTH-1:0] expected_value_i;
	input [DATA_WIDTH-1:0] actual_value_i;
	input pid_calculate_en_i;
	input [DATA_WIDTH-1:0] PID_parameter_P;
	input [DATA_WIDTH-1:0] PID_parameter_I;
	input [DATA_WIDTH-1:0] PID_parameter_D;
	output pid_feedback_ack_o;
	output pid_feedback_dir_o;
	output [DATA_WIDTH-1:0] pid_feedback_value_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [DATA_WIDTH-1:0] expected_value_i;
	wire [DATA_WIDTH-1:0] actual_value_i;
	wire pid_calculate_en_i;
	wire [DATA_WIDTH-1:0] PID_parameter_P;
	wire [DATA_WIDTH-1:0] PID_parameter_I;
	wire [DATA_WIDTH-1:0] PID_parameter_D;
	wire pid_feedback_ack_o;
	wire pid_feedback_dir_o;
	wire [DATA_WIDTH-1:0] pid_feedback_value_o;

	//----Code starts here: integrated by Robei-----
	localparam  SUM_ERROR_MAX   =   16'd2000;
	
	reg[7:0] pid_calculate_en_i_delay;
	
	reg[DATA_WIDTH-1:0] curr_error;   //当前误差
	reg[DATA_WIDTH-1:0] last_error;   //上一时刻误差
	reg[DATA_WIDTH-1:0] sum_error;    //误差累积
	reg       sum_error_dir;//误差累积方向
	reg[DATA_WIDTH-1:0] D_error;
	
	wire[DATA_WIDTH*2-1:0] P_MUL;
	reg[DATA_WIDTH-1:0] P_value;
	reg       P_dir;  
	
	wire[DATA_WIDTH*2-1:0] I_MUL;
	reg[DATA_WIDTH-1:0] I_value;
	reg       I_dir;
	
	wire[DATA_WIDTH*2-1:0] D_MUL;
	reg[DATA_WIDTH-1:0] D_value;
	reg       D_dir;
	
	reg[DATA_WIDTH-1:0] PI_sum_value;
	reg       PI_sum_dir;
	
	reg[DATA_WIDTH-1:0] PID_sum_value;
	reg       PID_sum_dir;
	
	assign pid_feedback_ack_o   = pid_calculate_en_i_delay == 8'b100_000_00 ? 1'b1 : 1'b0; 
	
	assign pid_feedback_value_o = ( PID_sum_value > P_FB_MAX ) ? P_FB_MAX : PID_sum_value;
	assign pid_feedback_dir_o   = PID_sum_dir;
	
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 ) 
	        pid_calculate_en_i_delay <= 'd0;
	    else if( pid_calculate_en_i_delay == 'd0)
	        pid_calculate_en_i_delay <= {7'b000_0000,pid_calculate_en_i};
	    else
	        pid_calculate_en_i_delay <= {pid_calculate_en_i_delay[6:0],1'b0};
	end
	
	//计算P
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0 ) begin
	        curr_error <= 'd0;
	        P_dir      <= 1'b0;
	    end
	    else if( pid_calculate_en_i ==  1'b1 )
	        if( expected_value_i > actual_value_i) begin
	            curr_error <= expected_value_i - actual_value_i;
	            P_dir      <= 1'b0;
	        end
	        else begin
	            curr_error <= actual_value_i - expected_value_i;
	            P_dir      <= 1'b1;
	        end
	    else begin
	        curr_error <= curr_error;
	        P_dir      <= P_dir;
	    end
	end 
	
	
	// mult_gen_16x16 mult_gen_16x16_v0
	// (
	//     .A          (     curr_error      ),
	//     .B          (     PID_parameter_P ),
	//     .P          (     P_MUL           )
	// );
	
	assign P_MUL = curr_error * PID_parameter_P;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 )
	        P_value <= 'd0;
	    else if( pid_calculate_en_i_delay == 8'b000_000_10 )
	        P_value <= ((P_MUL) >> 7) + ((P_MUL) >> 9);
	    else
	        P_value <= P_value;
	end
	
	
	//计算I
	always@( posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0) begin
	        sum_error <= 'd0;
	        sum_error_dir <= 1'b0;
	    end
	    else if( pid_calculate_en_i_delay == 8'b000_000_01 ) begin
	        if( curr_error > 'd1000 ) begin  //积分分离
	            sum_error <= 'd0;
	            sum_error_dir <= sum_error_dir;
	        end
	        else if( P_dir == sum_error_dir) begin
	            sum_error <= ((sum_error + curr_error) > SUM_ERROR_MAX ) ? SUM_ERROR_MAX : sum_error + curr_error; //限制幅值
	            sum_error_dir <= sum_error_dir;
	        end
	        else if( sum_error > curr_error) begin
	            sum_error <= 'd0;//sum_error - curr_error;
	            sum_error_dir <= sum_error_dir;
	        end
	        else begin
	            sum_error <= 'd0;//curr_error - sum_error;
	            sum_error_dir <= P_dir;
	        end
	    end  
	    else begin
	        sum_error <= sum_error;
	        sum_error_dir <= sum_error_dir;
	    end
	end
	
	
	// mult_gen_16x16 mult_gen_16x16_v1
	// (
	//     .A          (     sum_error      ),
	//     .B          (     PID_parameter_I ),
	//     .P          (     I_MUL           )
	// );
	
	assign I_MUL  = sum_error * PID_parameter_I;
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0 ) begin
	        I_value <= 'd0;
	        I_dir   <=  1'b0;
	    end
	    else if( pid_calculate_en_i_delay == 8'b000_001_00) begin
	        I_value <= ((I_MUL) >> 7) + ((I_MUL) >> 9);
	        I_dir   <= sum_error_dir;
	    end
	    else begin
	        I_value <= I_value;
	        I_dir   <= I_dir;
	    end
	end
	
	
	
	//计算D
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0) begin
	        D_error <= 'd0;
	        last_error <= 'd0;
	        D_dir <= 1'b0;
	    end
	    else if( pid_calculate_en_i_delay == 8'b000_000_01 ) begin
	        if( curr_error > last_error) begin
	            D_error <= curr_error - last_error;
	            D_dir   <= 1'b0;
	        end
	        else begin
	            D_error <= last_error - curr_error;
	            D_dir   <= 1'b1;
	        end
	        last_error <= curr_error;
	    end
	    else begin
	        D_error <= D_error;
	        last_error <= last_error;
	        D_dir <= D_dir;
	    end
	end
	
	
	// mult_gen_16x16 mult_gen_16x16_v2
	// (
	//     .A          (     D_error         ),
	//     .B          (     PID_parameter_D ),
	//     .P          (     D_MUL           )
	// );
	
	assign D_MUL = D_error * PID_parameter_D;
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0)
	        D_value <= 'd0;
	    else if( pid_calculate_en_i_delay == 8'b000_001_00)
	        D_value <= ((D_MUL) >> 7) + ((D_MUL) >> 9);
	    else
	        D_value <= D_value;
	end
	
	
	
	//求和
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0) begin
	        PI_sum_value <= 'd0;
	        PI_sum_dir   <= 1'b0;
	    end
	    else if( pid_calculate_en_i_delay == 8'b000_100_00) begin
	        if( P_dir == I_dir) begin
	            PI_sum_value <= P_value + I_value;
	            PI_sum_dir   <= P_dir;
	        end
	        else if( P_value >= I_value) begin
	            PI_sum_value <= P_value - I_value;
	            PI_sum_dir <= P_dir;
	        end
	        else begin
	            PI_sum_value <= I_value - P_value;
	            PI_sum_dir   <= I_dir;
	        end
	    end
	    else begin
	        PI_sum_value <= PI_sum_value;
	        PI_sum_dir   <= PI_sum_dir;
	    end
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0) begin
	        PID_sum_value <= 'd0;
	        PID_sum_dir   <= 1'b0;
	    end
	    else if( pid_calculate_en_i_delay == 8'b001_000_00) begin
	        if(PI_sum_dir == D_dir) begin
	            PID_sum_value <= PI_sum_value + D_value;
	            PID_sum_dir   <= PI_sum_dir;
	        end
	        else if( PI_sum_value >= D_value) begin
	            PID_sum_value <= PI_sum_value - D_value;
	            PID_sum_dir   <= PI_sum_dir;
	        end
	        else begin
	            PID_sum_value <= D_value - PI_sum_value;
	            PID_sum_dir   <= D_dir;
	        end
	    end
	    else begin
	        PID_sum_value <= PID_sum_value;
	        PID_sum_dir   <= PID_sum_dir;
	    end
	end
	
endmodule    //controller_PID

