module controller_Speed_loop(
	sys_clk_i,
	sys_rst_n_i,
	c_speed_loop_en_i,
	motor_spin_dir_i,
	motor_rpm_set_i,
	encoder_direction_i,
	encoder_speed_i,
	c_speed_loop_dir_o,
	c_speed_loop_rmp_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input c_speed_loop_en_i;
	input motor_spin_dir_i;
	input [15:0] motor_rpm_set_i;
	input encoder_direction_i;
	input [15:0] encoder_speed_i;
	output c_speed_loop_dir_o;
	output [15:0] c_speed_loop_rmp_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire c_speed_loop_en_i;
	wire motor_spin_dir_i;
	wire [15:0] motor_rpm_set_i;
	wire encoder_direction_i;
	wire [15:0] encoder_speed_i;
	reg c_speed_loop_dir_o;
	reg [15:0] c_speed_loop_rmp_o;

	//----Code starts here: integrated by Robei-----
	reg dir_switch_flag;  //速度切换标志
	
	//速度切换标志
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 )
	        dir_switch_flag <= 1'b0;
	    else if( c_speed_loop_en_i == 1'b1 )
	        if(( encoder_direction_i != motor_spin_dir_i ) && encoder_speed_i > 'd50) //方向不一致时，速度大于5RPM，需要减速后进行方向切换
	            dir_switch_flag <= 1'b1;
	        else if( ( encoder_direction_i != motor_spin_dir_i ) && encoder_speed_i <= 'd50)
	             dir_switch_flag <= 1'b0;
	        else if( encoder_direction_i == motor_spin_dir_i )
	            dir_switch_flag <= 1'b0;
	        else
	            dir_switch_flag <= 1'b0;
	    else
	        dir_switch_flag <= 1'b0;
	    
	end
	
	
	//设置速度环 方向输出
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 )
	        c_speed_loop_dir_o <= motor_spin_dir_i;
	    else if( c_speed_loop_en_i == 1'b1 )
	        if( encoder_speed_i <= 'd50 ) //速度低的时候，进行速度的切换
	            c_speed_loop_dir_o <= motor_spin_dir_i;
	        else
	            c_speed_loop_dir_o <= c_speed_loop_dir_o;
	    else
	        c_speed_loop_dir_o <= motor_spin_dir_i;
	end
	
	//设置速度环 期望速度输出
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0)
	        c_speed_loop_rmp_o <= 'd0;
	    else if( c_speed_loop_en_i == 1'b1) begin
	        if( dir_switch_flag == 1'b1 )
	            c_speed_loop_rmp_o <= 'd0;
	        else
	            c_speed_loop_rmp_o <= motor_rpm_set_i;
	    end
	    else
	        c_speed_loop_rmp_o <= 'd0;
	end
	
endmodule    //controller_Speed_loop

