module dc_motor_driver(
	sys_clk_i,
	sys_rst_n_i,
	motor_spin_dir_i,
	motor_rpm_set_i,
	motor_acc_set_i,
	Speed_PID_parameter_P,
	Speed_PID_parameter_I,
	Speed_PID_parameter_D,
	motor_encoder_A_i,
	motor_encoder_B_i,
	motor_spin_dir_o,
	controller_spin_dir_o,
	motor_pwm_driver_o,
	pulse_data);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input motor_spin_dir_i;
	input [15:0] motor_rpm_set_i;
	input [15:0] motor_acc_set_i;
	input [15:0] Speed_PID_parameter_P;
	input [15:0] Speed_PID_parameter_I;
	input [15:0] Speed_PID_parameter_D;
	input motor_encoder_A_i;
	input motor_encoder_B_i;
	output motor_spin_dir_o;
	output controller_spin_dir_o;
	output motor_pwm_driver_o;
	input [31:0] pulse_data;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire motor_spin_dir_i;
	wire [15:0] motor_rpm_set_i;
	wire [15:0] motor_acc_set_i;
	wire [15:0] Speed_PID_parameter_P;
	wire [15:0] Speed_PID_parameter_I;
	wire [15:0] Speed_PID_parameter_D;
	wire motor_encoder_A_i;
	wire motor_encoder_B_i;
	wire motor_spin_dir_o;
	wire controller_spin_dir_o;
	wire motor_pwm_driver_o;
	wire [31:0] pulse_data;
	wire [10:0] controller2_pwm_duty_o;
	wire [15:0] encoder1_encoder_speed_o;
	wire [15:0] encoder1_encoder_acc_o;
	wire encoder1_encoder_value_valid_o;
	wire encoder1_encoder_direction_o;

	//----Code starts here: integrated by Robei-----
	wire        encoder_acc_direction;
	//---Module instantiation---
	encoder encoder1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.encoder_en_i(1'b1),
		.motor_encoder_A_i(motor_encoder_A_i),
		.motor_encoder_B_i(motor_encoder_B_i),
		.encoder_value_valid_o(encoder1_encoder_value_valid_o),
		.encoder_direction_o(encoder1_encoder_direction_o),
		.encoder_acc_direction_o(encoder_acc_direction),
		.encoder_speed_o(encoder1_encoder_speed_o),
		.encoder_acc_o(encoder1_encoder_acc_o),
		.pulse_data(pulse_data));

	controller controller2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir_i(motor_spin_dir_i),
		.motor_rpm_set_i(motor_rpm_set_i),
		.motor_acc_set_i(motor_acc_set_i),
		.motor_rpm_max_i( ),
		.Speed_PID_parameter_P(Speed_PID_parameter_P),
		.Speed_PID_parameter_I(Speed_PID_parameter_I),
		.Speed_PID_parameter_D(Speed_PID_parameter_D),
		.encoder_value_valid_i(encoder1_encoder_value_valid_o),
		.encoder_direction_i(encoder1_encoder_direction_o),
		.encoder_speed_i(encoder1_encoder_speed_o),
		.encoder_acc_i(encoder1_encoder_acc_o),
		.pwm_duty_o(controller2_pwm_duty_o),
		.controller_spin_dir_o(controller_spin_dir_o));

	pwm_generate pwm_generate3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.pwm_en_i(1'b1),
		.pwm_duty_i(controller2_pwm_duty_o),
		.pwm_io_o(motor_pwm_driver_o));

endmodule    //dc_motor_driver

