module encoder(
	sys_clk_i,
	sys_rst_n_i,
	encoder_en_i,
	motor_encoder_A_i,
	motor_encoder_B_i,
	encoder_value_valid_o,
	encoder_direction_o,
	encoder_acc_direction_o,
	encoder_speed_o,
	encoder_acc_o,
	pulse_data);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input encoder_en_i;
	input motor_encoder_A_i;
	input motor_encoder_B_i;
	output encoder_value_valid_o;
	output encoder_direction_o;
	output encoder_acc_direction_o;
	output [15:0] encoder_speed_o;
	output [15:0] encoder_acc_o;
	input [31:0] pulse_data;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire encoder_en_i;
	wire motor_encoder_A_i;
	wire motor_encoder_B_i;
	reg encoder_value_valid_o;
	reg encoder_direction_o;
	wire encoder_acc_direction_o;
	wire [15:0] encoder_speed_o;
	wire [15:0] encoder_acc_o;
	wire [31:0] pulse_data;
	wire encoder_AB_detect3_encoder_AB_detect_valid_o;
	wire encoder_AB_detect3_encoder_AB_detect_dir_o;
	wire [15:0] encoder_Phase_count2_encoder_Phase_count_o;

	//----Code starts here: integrated by Robei-----
	wire timer_ack;
	wire encoder_Phase_count_dir;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i ) begin
		if( sys_rst_n_i == 1'b0 )
			encoder_value_valid_o <= 1'b0;
		else if( timer_ack == 1'b1 )
			encoder_value_valid_o <= 1'b1;
		else
			encoder_value_valid_o <= 1'b0;
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 )
	        encoder_direction_o <= 1'b0;
	    else if( timer_ack == 1'b1 )
	        encoder_direction_o <= encoder_Phase_count_dir;
	    else
	        encoder_direction_o <= encoder_direction_o;
	end
	
	//---Module instantiation---
	timer #( 8'd30, 20'd16_665) timer1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.timer_cnt_en_i(encoder_en_i),
		.timer_cnt_clr_i(1'b0),
		.timer_ack_o(timer_ack));

	encoder_Phase_count encoder_Phase_count2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.encoder_Phase_count_clear_i(timer_ack),
		.encoder_Phase_count_en_i(encoder_en_i),
		.encoder_AB_detect_valid_i(encoder_AB_detect3_encoder_AB_detect_valid_o),
		.encoder_AB_detect_dir_i(encoder_AB_detect3_encoder_AB_detect_dir_o),
		.encoder_Phase_count_dir_o(encoder_Phase_count_dir),
		.encoder_Phase_count_o(encoder_Phase_count2_encoder_Phase_count_o));

	encoder_AB_detect encoder_AB_detect3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.encoder_AB_detect_en_i(encoder_en_i),
		.motor_encoder_A_i(motor_encoder_A_i),
		.motor_encoder_B_i(motor_encoder_B_i),
		.encoder_AB_detect_valid_o(encoder_AB_detect3_encoder_AB_detect_valid_o),
		.encoder_AB_detect_dir_o(encoder_AB_detect3_encoder_AB_detect_dir_o));

	encoder_SpeedAcc_calculate encoder_SpeedAcc_calculate4(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cal_en_i(timer_ack),
		.encoder_Phase_count_dir_i(encoder_Phase_count_dir),
		.encoder_Phase_count_i(encoder_Phase_count2_encoder_Phase_count_o),
		.encoder_speed_o(encoder_speed_o),
		.encoder_acc_o(encoder_acc_o),
		.encoder_acc_dir_o(encoder_acc_direction_o),
		.pulse_data(pulse_data));

endmodule    //encoder

