module encoder_SpeedAcc_calculate(
	sys_clk_i,
	sys_rst_n_i,
	cal_en_i,
	encoder_Phase_count_dir_i,
	encoder_Phase_count_i,
	encoder_speed_o,
	encoder_acc_o,
	encoder_acc_dir_o,
	pulse_data);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input cal_en_i;
	input encoder_Phase_count_dir_i;
	input [15:0] encoder_Phase_count_i;
	output [15:0] encoder_speed_o;
	output [15:0] encoder_acc_o;
	output encoder_acc_dir_o;
	input [31:0] pulse_data;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire cal_en_i;
	wire encoder_Phase_count_dir_i;
	wire [15:0] encoder_Phase_count_i;
	reg [15:0] encoder_speed_o;
	reg [15:0] encoder_acc_o;
	reg encoder_acc_dir_o;
	wire [31:0] pulse_data;

	//----Code starts here: integrated by Robei-----
	// speed = (X*1分钟)/(PPR*R*T0) = 30.77 * X(脉冲数) 
	//  speed = ( 16 +  8 + 4 + 2)  X(脉冲数)  
	//  acc = speed - speed0  当前时刻的速度 - 前一时刻的速度
	reg[15:0] encoder_speed_d0;  //暂存上一次的速度
	
	
	wire[15:0] encoder_speed;
	
	wire [7:0] d7;
	wire [7:0] d6;
	wire [7:0] d5;
	wire [7:0] d4;
	wire [7:0] d3;
	wire [7:0] d2;
	wire [7:0] d1;
	wire [7:0] d0;
	
	assign encoder_speed = ( encoder_Phase_count_i << d7 ) + ( encoder_Phase_count_i << d6 ) + ( encoder_Phase_count_i << d5 ) + ( encoder_Phase_count_i << d4 ) + ( encoder_Phase_count_i << d3 ) + ( encoder_Phase_count_i << d2 ) + ( encoder_Phase_count_i << d1 ) + ( encoder_Phase_count_i << d0 ) ;
	//assign encoder_speed = ( encoder_Phase_count_i << 3 ) + ( encoder_Phase_count_i << 2 );
	
	always@( posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 ) begin
	        encoder_speed_d0 <= 16'd0;
	        encoder_speed_o  <= 16'd0;
	        encoder_acc_o    <= 16'd0;
	        encoder_acc_dir_o<= 1'b0;
	    end
	    else if( cal_en_i == 1'b1 ) begin
	        encoder_speed_d0 <= encoder_speed_o;
	        encoder_speed_o  <= encoder_speed;
	        encoder_acc_o    <= (encoder_speed > encoder_speed_d0) ? encoder_speed - encoder_speed_d0 : encoder_speed_d0 - encoder_speed;
	        encoder_acc_dir_o<= (encoder_speed > encoder_speed_d0) ? 1'b1 : 1'b0;
	    end
	    else begin
	        encoder_speed_d0 <= encoder_speed_d0;
	        encoder_speed_o  <= encoder_speed_o;
	        encoder_acc_o    <= encoder_acc_o;
	        encoder_acc_dir_o<= encoder_acc_dir_o;
	    end
	end
	
	//---Module instantiation---
	data_split data_split1(
		.data(pulse_data),
		.d7(d7),
		.d6(d6),
		.d5(d5),
		.d4(d4),
		.d3(d3),
		.d2(d2),
		.d1(d1),
		.d0(d0));

endmodule    //encoder_SpeedAcc_calculate

