module encoder_AB_detect(
	sys_clk_i,
	sys_rst_n_i,
	encoder_AB_detect_en_i,
	motor_encoder_A_i,
	motor_encoder_B_i,
	encoder_AB_detect_valid_o,
	encoder_AB_detect_dir_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input encoder_AB_detect_en_i;
	input motor_encoder_A_i;
	input motor_encoder_B_i;
	output encoder_AB_detect_valid_o;
	output encoder_AB_detect_dir_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire encoder_AB_detect_en_i;
	wire motor_encoder_A_i;
	wire motor_encoder_B_i;
	wire encoder_AB_detect_valid_o;
	wire encoder_AB_detect_dir_o;

	//----Code starts here: integrated by Robei-----
	localparam MAX_TIMEOUT =    24'd500_0000;
	
	reg encoder_A_d0,encoder_A_d1;
	reg encoder_B_d0,encoder_B_d1;
	
	reg encoder_AB_detect_dir_reg;
	
	wire encoder_A_posedge , encoder_A_negedge ;
	wire encoder_B_posedge , encoder_B_negedge ;
	
	
	reg[5:0] step;
	
	reg[23:0]  timer;
	
	//检测A,B相的上升下降沿
	assign encoder_A_posedge = encoder_A_d0 & (~encoder_A_d1);
	assign encoder_A_negedge = (~encoder_A_d0) & encoder_A_d1;
	
	assign encoder_B_posedge = encoder_B_d0 & (~encoder_B_d1);
	assign encoder_B_negedge = (~encoder_B_d0) & encoder_B_d1;
	
	
	assign encoder_AB_detect_dir_o   = encoder_AB_detect_dir_reg;
	assign encoder_AB_detect_valid_o = ( step == 6'b10_0000 ) ? 1'b1 : 1'b0;
	
	//对输入的A,B相进行打拍
	always@(posedge sys_clk_i or negedge sys_rst_n_i ) begin
	    if( sys_rst_n_i == 1'b0 )begin
	        encoder_A_d0 <= 1'b0;
	        encoder_A_d1 <= 1'b0;
	        encoder_B_d0 <= 1'b0;
	        encoder_B_d1 <= 1'b0;
	    end
	    else begin
	        encoder_A_d0 <= motor_encoder_A_i;
	        encoder_A_d1 <= encoder_A_d0;
	        encoder_B_d0 <= motor_encoder_B_i;
	        encoder_B_d1 <= encoder_B_d0;
	    end
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0 ) begin
	        step <= 6'b00_0000;
	        encoder_AB_detect_dir_reg <= 1'b0;
	    end
	    else begin
	        case (step)
	        6'b00_0000: begin                 //处理第一个边沿
	            if( (encoder_A_posedge  | encoder_B_posedge) && encoder_AB_detect_en_i == 1'b1)  
	                step <= 6'b00_0001;
	            else
	                step <= step;
	        end
	        6'b00_0001: begin  //处理第二个边沿
	            if( encoder_A_posedge == 1'b1)
	                if( encoder_B_d0 == 1'b1) begin
	                    step <= 6'b00_0100;
	                    encoder_AB_detect_dir_reg <= 1'b0;
	                end
	                else
	                    step <= 6'b00_0000;
	            else if( encoder_B_posedge == 1'b1)
	                if( encoder_A_d0 == 1'b1) begin
	                    step <= 6'b00_0010;
	                    encoder_AB_detect_dir_reg <= 1'b1;
	                end
	                else
	                    step <= 6'b00_0000;
	            else if( encoder_A_negedge | encoder_B_negedge)   //检测到下降沿 表示错误 
	                step <= 6'b00_0000;
	            else  
	                step <= step;  //需进行超时处理
	        end
	        6'b00_0010: begin //处理第三个边沿
	            if( encoder_A_negedge == 1'b1 )
	                if( encoder_B_d0 == 1'b1)
	                    step <= 6'b00_1000;
	                else 
	                    step <= 6'b00_0000;
	            else if( encoder_B_negedge == 1'b1 )
	                step <= 6'b00_0000;
	            else
	                step <= step;
	        end
	        6'b00_0100: //处理第三个边沿
	            if( encoder_B_negedge == 1'b1 )
	                if( encoder_A_d0 == 1'b1)
	                    step <= 6'b01_0000;
	                else 
	                    step <= 6'b00_0000;
	            else if( encoder_A_negedge == 1'b1 )
	                step <= 6'b00_0000;
	            else
	                step <= step;
	        6'b00_1000: begin//处理第四个边沿
	            if( encoder_B_negedge == 1'b1)
	                if( encoder_A_d0 == 1'b0)
	                    step <= 6'b10_0000;
	                else
	                    step <= 6'b00_0000;
	            else if( encoder_A_posedge == 1'b1)
	                step <= 6'b00_0000;
	            else
	                step <= step;
	        end
	        6'b01_0000: begin  //处理第四个边沿
	            if( encoder_A_negedge == 1'b1)
	                if( encoder_B_d0 == 1'b0)
	                    step <= 6'b10_0000;
	                else
	                    step <= 6'b00_0000;
	            else if( encoder_B_posedge == 1'b1)
	                step <= 6'b00_0000;
	            else
	                step <= step;
	        end
	        6'b10_0000: 
	            step <= 6'b00_0000;
	        default: begin step <= 6'b00_0000 ;encoder_AB_detect_dir_reg = 1'b0; end
	        endcase
	    end
	end
	
endmodule    //encoder_AB_detect

