module encoder_Phase_count(
	sys_clk_i,
	sys_rst_n_i,
	encoder_Phase_count_clear_i,
	encoder_Phase_count_en_i,
	encoder_AB_detect_valid_i,
	encoder_AB_detect_dir_i,
	encoder_Phase_count_dir_o,
	encoder_Phase_count_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input encoder_Phase_count_clear_i;
	input encoder_Phase_count_en_i;
	input encoder_AB_detect_valid_i;
	input encoder_AB_detect_dir_i;
	output encoder_Phase_count_dir_o;
	output [15:0] encoder_Phase_count_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire encoder_Phase_count_clear_i;
	wire encoder_Phase_count_en_i;
	wire encoder_AB_detect_valid_i;
	wire encoder_AB_detect_dir_i;
	wire encoder_Phase_count_dir_o;
	wire [15:0] encoder_Phase_count_o;

	//----Code starts here: integrated by Robei-----
	reg[15:0]   encoder_Phase_Cnt_dir0;
	reg[15:0]   encoder_Phase_Cnt_dir1;
	
	
	
	assign encoder_Phase_count_dir_o = ( encoder_Phase_Cnt_dir0 > encoder_Phase_Cnt_dir1 ) ? 1'b0 : 1'b1;
	assign encoder_Phase_count_o     = ( encoder_Phase_Cnt_dir0 > encoder_Phase_Cnt_dir1 ) ? (encoder_Phase_Cnt_dir0 - encoder_Phase_Cnt_dir1):  (encoder_Phase_Cnt_dir1 - encoder_Phase_Cnt_dir0);
	
	//编码器脉冲计数
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0) begin
	        encoder_Phase_Cnt_dir0 <= 16'd0;
	        encoder_Phase_Cnt_dir1 <= 16'd0;
	    end
	    else if( encoder_Phase_count_clear_i == 1'b1 ) begin
	        encoder_Phase_Cnt_dir0 <= 16'd0;
	        encoder_Phase_Cnt_dir1 <= 16'd0;
	    end
	    else if( encoder_AB_detect_valid_i == 1'b1 )  //对两个方向的脉冲分别计数
	        if( encoder_AB_detect_dir_i == 1'b0 ) begin
	            encoder_Phase_Cnt_dir0 <= encoder_Phase_Cnt_dir0 + 1'b1;
	            encoder_Phase_Cnt_dir1 <= encoder_Phase_Cnt_dir1;
	        end
	        else begin
	            encoder_Phase_Cnt_dir0 <= encoder_Phase_Cnt_dir0;
	            encoder_Phase_Cnt_dir1 <= encoder_Phase_Cnt_dir1 + 1'b1;   
	        end
	    else begin
	        encoder_Phase_Cnt_dir0 <= encoder_Phase_Cnt_dir0;
	        encoder_Phase_Cnt_dir1 <= encoder_Phase_Cnt_dir1;
	    end
	end
	
endmodule    //encoder_Phase_count

