module pwm_generate(
	sys_clk_i,
	sys_rst_n_i,
	pwm_en_i,
	pwm_duty_i,
	pwm_io_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input pwm_en_i;
	input [10:0] pwm_duty_i;
	output pwm_io_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire pwm_en_i;
	wire [10:0] pwm_duty_i;
	reg pwm_io_o;

	//----Code starts here: integrated by Robei-----
	//pwm 频率 = (sys_clk_i / Frequency_division_coe*2 + 2) / 'd1024
	parameter Frequency_division_coe = 8'd3; //50Mhz~8.14Khz  33.333Mhz~4.07Khz
	
	reg[7:0]   pwm_sys_div_cnt;//pwm分频计数    
	reg[10:0]   pwm_div_cnt;    //pwm高低电平计数
	//reg         pwm_sys_clk; 
	
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        pwm_sys_div_cnt <= 16'd0;
	    else if( pwm_en_i == 1'b0)
	        pwm_sys_div_cnt <= 16'd0;
	    else if( pwm_en_i == 1'b1)
	        if( pwm_sys_div_cnt == Frequency_division_coe)
	            pwm_sys_div_cnt <= 16'd0;
	        else
	            pwm_sys_div_cnt <= pwm_sys_div_cnt + 1'b1;
	    else
	        pwm_sys_div_cnt <= pwm_sys_div_cnt;
	end
	
	// always @(posedge sys_clk_i or negedge sys_rst_n_i) begin
	//     if( sys_rst_n_i == 1'b0)
	//         pwm_sys_clk <= 1'b0;
	//     else if( pwm_sys_div_cnt == Frequency_division_coe)
	//         pwm_sys_clk <= ~pwm_sys_clk;
	//     else
	//         pwm_sys_clk <= pwm_sys_clk;
	// end
	
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        pwm_div_cnt <= 11'd0;
	    else if( pwm_en_i == 1'b0)
	        pwm_div_cnt <= 11'd0;
	    else if( pwm_sys_div_cnt == Frequency_division_coe)
	        pwm_div_cnt <= pwm_div_cnt + 1'b1;
	    else
	        pwm_div_cnt <= pwm_div_cnt;
	end
	
	
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        pwm_io_o <= 1'b0;
	    else if( pwm_en_i == 1'b0)
	        pwm_io_o <= 1'b1;
	    else if( pwm_div_cnt == 11'd2047 && pwm_sys_div_cnt == Frequency_division_coe)
	        pwm_io_o <= 1'b1;
	    else if(pwm_div_cnt == pwm_duty_i && pwm_sys_div_cnt == Frequency_division_coe)
	        pwm_io_o <= 1'b0;
	    else
	        pwm_io_o <= pwm_io_o;
	end
endmodule    //pwm_generate

