module steer_pwm(
	sys_clk_i,
	sys_rst_n_i,
	theta,
	pwm_gen_en,
	pwm_out);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [31:0] theta;
	input pwm_gen_en;
	output pwm_out;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [31:0] theta;
	wire pwm_gen_en;
	reg pwm_out;

	//----Code starts here: integrated by Robei-----
	wire [31:0] counter_arr;
	wire [31:0] counter_ccr;
	
	assign counter_arr = 32'd666667;
	//assign counter_ccr = ((theta >>> 16) < 32'd0) ? 32'd0 :
	//										((theta >>> 16) > 32'd270) ? 32'd0 :
	//(650001 - ((theta >>> 9) + (theta >>> 10) + (theta >>> 11) + (theta >>> 12) + (theta >>> 14) + (theta >>> 15) + (theta >>> 17) + (theta >>> 18) + (theta >>> 19) + (theta >>> 21) + (theta >>> 24) + (theta >>> 26)));
	
	assign counter_ccr = (650001 - ((theta >>> 9) + (theta >>> 10) + (theta >>> 11) + (theta >>> 12) + (theta >>> 14) + (theta >>> 15) + (theta >>> 17) + (theta >>> 18) + (theta >>> 19) + (theta >>> 21) + (theta >>> 24) + (theta >>> 26)));
	
	reg [31:0]pwm_gen_cnt;   //定义32位产生pwm的计数器
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(!sys_rst_n_i)
		pwm_gen_cnt <= 32'd1;
	else if(pwm_gen_en)
	begin
		if(pwm_gen_cnt <= 32'd1)
			pwm_gen_cnt <= counter_arr;       //计数减到1，加载预重装寄存器值
		else	
			pwm_gen_cnt <= pwm_gen_cnt - 1'b1;//计数器自减1
	end
	else
		pwm_gen_cnt <= counter_arr;	        //未使能时，计数器值等于预重装寄存器值
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(!sys_rst_n_i)                          //复位时，PWM输出低电平
		pwm_out <= 1'b0;
	else if(pwm_gen_cnt <= counter_ccr)   //计数值小于比较值，PWM输出低电平
		pwm_out <= 1'b0;
	else
		pwm_out <= 1'b1;                    //计数值大于比较值，PWM输出高电平
	
	
endmodule    //steer_pwm

