module all_direction_wheel_three_calculate(
	sys_clk_i,
	sys_rst_n_i,
	all_direction_wheel_en,
	x_speed,
	y_speed,
	z_speed,
	M1_speed_out,
	M2_speed_out,
	M3_speed_out);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input all_direction_wheel_en;
	input [15:0] x_speed;
	input [15:0] y_speed;
	input [15:0] z_speed;
	output [15:0] M1_speed_out;
	output [15:0] M2_speed_out;
	output [15:0] M3_speed_out;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire all_direction_wheel_en;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	reg [15:0] M1_speed_out;
	reg [15:0] M2_speed_out;
	reg [15:0] M3_speed_out;

	//----Code starts here: integrated by Robei-----
	//所有参数均扩大100倍
	parameter para_x = 86;
	parameter para_y = 50;
	parameter para_z = 100;
	
	reg [15:0] M1_speed_out_r;
	reg [15:0] M2_speed_out_r;
	reg [15:0] M3_speed_out_r;
	
	reg [15:0] M1_speed_out_t;
	reg [15:0] M2_speed_out_t;
	reg [15:0] M3_speed_out_t;
	
	reg [15:0] M1_speed_out_o;
	reg [15:0] M2_speed_out_o;
	reg [15:0] M3_speed_out_o;
	
	//M1_speed_out
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0) begin
	    M1_speed_out <= 'd0;
		M1_speed_out_r <= 'd0;
		M1_speed_out_t <= 'd0;
		M1_speed_out_o <= 'd0;
	end
	else if(all_direction_wheel_en == 1'b1) begin
	    M1_speed_out_r <= y_speed * 100 + z_speed * para_z;
		if (M1_speed_out_r[15] == 1'b0)
			M1_speed_out <= (M1_speed_out_r >> 7) + (M1_speed_out_r >> 9);
		else if (M1_speed_out_r[15] == 1'b1) begin
			M1_speed_out_t <= (~M1_speed_out_r + 1);
			M1_speed_out_o <= (M1_speed_out_t >> 7) + (M1_speed_out_t >> 9);
			M1_speed_out <= (~M1_speed_out_o+1);
		end
	end
	else 
	    M1_speed_out <= M1_speed_out;
	    
	//M2_speed_out	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0) begin
	    M2_speed_out <= 'd0;
		M2_speed_out_r <= 'd0;
		M2_speed_out_t <= 'd0;
		M2_speed_out_o <= 'd0;
	end
	else if(all_direction_wheel_en == 1'b1) begin
		M2_speed_out_r <= (z_speed * para_z) - (x_speed * para_x) - (y_speed * para_y);
		if (M2_speed_out_r[15] == 1'b0)
			M2_speed_out <= (M2_speed_out_r >> 7) + (M2_speed_out_r >> 9);
		else if (M2_speed_out_r[15] == 1'b1) begin
			M2_speed_out_t <= (~M2_speed_out_r + 1);
			M2_speed_out_o <= (M2_speed_out_t >> 7) + (M2_speed_out_t >> 9);
			M2_speed_out <= (~M2_speed_out_o + 1);
		end
	end
	else 
	    M2_speed_out <= M2_speed_out;
	
	//M3_speed_out	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0) begin
	    M3_speed_out <= 'd0;
		M3_speed_out_r <= 'd0;
		M3_speed_out_t <= 'd0;
		M3_speed_out_o <= 'd0;
	end
	else if(all_direction_wheel_en == 1'b1) begin
		M3_speed_out_r <= (x_speed * para_x) - (y_speed * para_y) - (z_speed * para_z);
		if (M3_speed_out_r[15] == 1'b0)
			M3_speed_out <= (M3_speed_out_r >> 7) + (M3_speed_out_r >> 9);
		else if (M3_speed_out_r[15] == 1'b1) begin
			M3_speed_out_t <= (~M3_speed_out_r + 1);
			M3_speed_out_o <= (M3_speed_out_t >> 7) + (M3_speed_out_t >> 9);
			M3_speed_out <= (~M3_speed_out_o + 1);
		end
	end
	else 
	    M3_speed_out <= M3_speed_out;
endmodule    //all_direction_wheel_three_calculate

