module all_direction_wheel_four_calculate(
	M1_speed_out,
	M2_speed_out,
	M3_speed_out,
	sys_clk_i,
	sys_rst_n_i,
	all_direction_wheel_en,
	x_speed,
	y_speed,
	z_speed,
	M4_speed_out,
	A_length_mm,
	B_length_mm);

	//---Ports declearation: generated by Robei---
	output [15:0] M1_speed_out;
	output [15:0] M2_speed_out;
	output [15:0] M3_speed_out;
	input sys_clk_i;
	input sys_rst_n_i;
	input all_direction_wheel_en;
	input [15:0] x_speed;
	input [15:0] y_speed;
	input [15:0] z_speed;
	output [15:0] M4_speed_out;
	input [15:0] A_length_mm;
	input [15:0] B_length_mm;

	reg [15:0] M1_speed_out;
	reg [15:0] M2_speed_out;
	reg [15:0] M3_speed_out;
	wire sys_clk_i;
	wire sys_rst_n_i;
	wire all_direction_wheel_en;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	reg [15:0] M4_speed_out;
	wire [15:0] A_length_mm;
	wire [15:0] B_length_mm;

	//----Code starts here: integrated by Robei-----
	/*
	四轮全向轮运动解算
	 车轮安装示意图：
	                          ^ X 方向
	                         /|\                      ------
	                          |                              \
	      FL(1)               |                 FR(2)         \
	     --------             |               ---------        \
	    |  \\    |            |               |    // |         \
	    |   \\   | -------------------------- |   //  |          \ 
	    |    \\  |            |               |  //   |           \
	     --------             |               --------             \  /
	                          |                                 _ __\/   Z 方向（顺时针为正）
	                          |                                      \
	                          |                             
	                          |
	                          |                         \
	                          + ————————————————————————> Y 方向                                      
	                          |                         /
	                          |
	                          |
	                          |
	       BL(4)                            BR(3)
	     --------           |                --------
	    |    //  |            |               |  \\    |
	    |   //   |--------------------------  |   \\   |
	    |  //    |                            |    \\  |
	     --------                              --------
	*/
	//A_length_mm为左右两个全向轮车宽的一半
	//B_length_mm为前后两个全向轮车宽的一半
	
	
	//M1_speed_out
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0)
	    M1_speed_out <= 'd0;
	else if(all_direction_wheel_en == 1'b1)
	    M1_speed_out <= x_speed + y_speed + z_speed* (A_length_mm + B_length_mm);
	else 
	    M1_speed_out <= M1_speed_out;
	    
	//M2_speed_out	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0)
	    M2_speed_out <= 'd0;
	else if(all_direction_wheel_en == 1'b1)
	    M2_speed_out <= x_speed - y_speed - z_speed* (A_length_mm + B_length_mm);
	else 
	    M2_speed_out <= M2_speed_out;
	
	//M3_speed_out	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0)
	    M3_speed_out <= 'd0;
	else if(all_direction_wheel_en == 1'b1)
	    M3_speed_out <= x_speed + y_speed - z_speed* (A_length_mm + B_length_mm);
	else 
	    M3_speed_out <= M3_speed_out;
	
	//M4_speed_out	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0)
	    M4_speed_out <= 'd0;
	else if(all_direction_wheel_en == 1'b1)
	    M4_speed_out <= x_speed - y_speed + z_speed* (A_length_mm + B_length_mm);
	else 
	    M4_speed_out <= M4_speed_out;
endmodule    //all_direction_wheel_four_calculate

