module dance_ctrl(
	clk_i,
	sys_rst_n_i,
	x_speed,
	y_speed,
	z_speed,
	dance_ack,
	clr_en);

	//---Ports declearation: generated by Robei---
	input clk_i;
	input sys_rst_n_i;
	output [15:0] x_speed;
	output [15:0] y_speed;
	output [15:0] z_speed;
	output dance_ack;
	input clr_en;

	wire clk_i;
	wire sys_rst_n_i;
	reg [15:0] x_speed;
	reg [15:0] y_speed;
	reg [15:0] z_speed;
	reg dance_ack;
	wire clr_en;

	//----Code starts here: integrated by Robei-----
	reg send_en;
	reg [31:0] cnt;
	
	//50ms
	always @ (posedge clk_i or negedge sys_rst_n_i)
	begin
		if (!sys_rst_n_i)
		begin
			cnt <= 'd0;
			dance_ack <= 1'b0;
		end
		else if (clr_en == 1'b1)
		begin
			cnt <= 'd0;
			dance_ack <= 1'b0;
		end
		else if (cnt<= 32'd2400) //2min½áÊø
		begin
			cnt <= cnt + 1'b1;
			dance_ack <= 1'b1;
		end
		else
		begin
			cnt <= cnt;
			dance_ack <= 1'b0;
		end
	end
	
	always @ (posedge clk_i or negedge sys_rst_n_i)
	begin
		if (!sys_rst_n_i)
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd00;
			z_speed <= 16'd00;
		end
		else if (cnt <= 'd20) //1s  zÕı×ª
			//z_speed <= 16'd20;
			z_speed <= 16'd0;
		else if (cnt <= 'd40) //2s z·´×ª
			//z_speed <= -16'd20;
			z_speed <= 16'd0;
		else if (cnt <= 'd60) //3s Í£Ö¹
			z_speed <= 16'd00;
		else if (cnt <= 'd70) //3.5s °Ú¶¯ X Y
		begin
			x_speed <= 16'd05;
			y_speed <= 16'd05;
		end
		else if (cnt <= 'd80) //4.0s °Ú¶¯ X -Y
		begin
			x_speed <= 16'd05;
			y_speed <= -16'd05;
		end
		else if (cnt <= 'd90) //4.5s °Ú¶¯ X Y
		begin
			x_speed <= 16'd05;
			y_speed <= 16'd05;
		end
		else if (cnt <= 'd100) //5s °Ú¶¯ X -Y
		begin
			x_speed <= 16'd05;
			y_speed <= -16'd05;
		end
		else if (cnt <= 'd110) //5.5s °Ú¶¯ X Y
		begin
			x_speed <= 16'd05;
			y_speed <= 16'd05;
		end
		else if (cnt <= 'd120) //6s °Ú¶¯ X -Y
		begin
			x_speed <= 16'd05;
			y_speed <= -16'd05;
		end
		else if (cnt <= 'd130) //6.5s °Ú¶¯ X Y
		begin
			x_speed <= 16'd05;
			y_speed <= 16'd05;
		end
		else if (cnt <= 'd140) //7s °Ú¶¯ X -Y
		begin
			x_speed <= 16'd05;
			y_speed <= -16'd05;
		end
		else if (cnt <= 'd150) //7.5s °Ú¶¯ X Y
		begin
			x_speed <= 16'd05;
			y_speed <= 16'd05;
		end
		else if (cnt <= 'd160) //8s °Ú¶¯ Í£Ö¹
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd00;
		end
		else if (cnt <= 'd180) //9s 8×Ö Y 90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd08;
		end
		else if (cnt <= 'd200) //10s 8×Ö X Y 60¡ã
		begin
			x_speed <= 16'd04;
			y_speed <= 16'd07;
		end
		else if (cnt <= 'd220) //11s 8×Ö X Y 45¡ã
		begin
			x_speed <= 16'd06;
			y_speed <= 16'd06;
		end
		else if (cnt <= 'd240) //12s 8×Ö X Y 30¡ã
		begin
			x_speed <= 16'd07;
			y_speed <= 16'd04;
		end
		else if (cnt <= 'd260) //13s 8×Ö Y 0¡ã
		begin
			x_speed <= 16'd08;
			y_speed <= 16'd00;
		end
		else if (cnt <= 'd280) //14s 8×Ö -X Y 30¡ã
		begin
			x_speed <= 16'd07;
			y_speed <= -16'd04;
		end
		else if (cnt <= 'd300) //15s 8×Ö -X Y 45¡ã
		begin
			x_speed <= 16'd06;
			y_speed <= -16'd06;
		end
		else if (cnt <= 'd320) //16s 8×Ö -X Y 60¡ã
		begin
			x_speed <= 16'd04;
			y_speed <= -16'd07;
		end
		else if (cnt <= 'd340) //17s 8×Ö -X  90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= -16'd08;
		end
		else if (cnt <= 'd360) //18s 8×Ö -X  90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= -16'd08;
		end
		else if (cnt <= 'd380) //19s 8×Ö -X Y 60¡ã
		begin
			x_speed <= 16'd04;
			y_speed <= -16'd07;
		end
		else if (cnt <= 'd400) //20s 8×Ö -X Y 45¡ã
		begin
			x_speed <= 16'd06;
			y_speed <= -16'd06;
		end
		else if (cnt <= 'd420) //21s 8×Ö -X Y 30¡ã
		begin
			x_speed <= 16'd07;
			y_speed <= -16'd04;
		end
		else if (cnt <= 'd440) //22s 8×Ö  Y 0¡ã
		begin
			x_speed <= 16'd08;
			y_speed <= 16'd00;
		end
		else if (cnt <= 'd460) //23s 8×Ö  X Y 30¡ã
		begin
			x_speed <= 16'd07;
			y_speed <= 16'd04;
		end
		else if (cnt <= 'd480) //24s 8×Ö  X Y 45¡ã
		begin
			x_speed <= 16'd06;
			y_speed <= 16'd06;
		end
		else if (cnt <= 'd500) //25s 8×Ö X Y 60¡ã
		begin
			x_speed <= 16'd04;
			y_speed <= 16'd07;
		end
		else if (cnt <= 'd520) //26s 8×Ö X  90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd08;
		end
		else if (cnt <= 'd540) //27s 8×Ö X 90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd08;
		end
		else if (cnt <= 'd560) //28s 8×Ö X -Y 60¡ã
		begin
			x_speed <= -16'd04;
			y_speed <= 16'd07;
		end
		else if (cnt <= 'd580) //29s 8×Ö X -Y 45¡ã
		begin
			x_speed <= -16'd06;
			y_speed <= 16'd06;
		end
		else if (cnt <= 'd600) //30s 8×Ö X -Y 30¡ã
		begin
			x_speed <= -16'd07;
			y_speed <= 16'd04;
		end
		else if (cnt <= 'd620) //31s 8×Ö  -Y 0¡ã
		begin
			x_speed <= -16'd08;
			y_speed <= 16'd00;
		end
		else if (cnt <= 'd640) //32s 8×Ö -X -Y 30¡ã
		begin
			x_speed <= -16'd07;
			y_speed <= -16'd04;
		end
		else if (cnt <= 'd660) //33s 8×Ö -X -Y 45¡ã
		begin
			x_speed <= -16'd06;
			y_speed <= -16'd06;
		end
		else if (cnt <= 'd680) //34s 8×Ö -X -Y 60¡ã
		begin
			x_speed <= -16'd04;
			y_speed <= -16'd07;
		end
		else if (cnt <= 'd700) //35s 8×Ö -X 90¡ã
		begin
			x_speed <= -16'd00;
			y_speed <= -16'd08;
		end
		else if (cnt <= 'd720) //36s 8×Ö -X 90¡ã
		begin
			x_speed <= -16'd00;
			y_speed <= -16'd08;
		end
		else if (cnt <= 'd740) //37s 8×Ö -X -Y 60¡ã
		begin
			x_speed <= -16'd04;
			y_speed <= -16'd07;
		end
		else if (cnt <= 'd760) //38s 8×Ö -X -Y 45¡ã
		begin
			x_speed <= -16'd06;
			y_speed <= -16'd06;
		end
		else if (cnt <= 'd780) //39s 8×Ö -X -Y 30¡ã
		begin
			x_speed <= -16'd07;
			y_speed <= -16'd04;
		end
		else if (cnt <= 'd800) //40s 8×Ö  -Y 0¡ã
		begin
			x_speed <= -16'd08;
			y_speed <= 16'd00;
		end
		else if (cnt <= 'd820) //41s 8×Ö X -Y 30¡ã
		begin
			x_speed <= -16'd07;
			y_speed <= 16'd04;
		end
		else if (cnt <= 'd840) //42s 8×Ö X -Y 45¡ã
		begin
			x_speed <= -16'd06;
			y_speed <= 16'd06;
		end
		else if (cnt <= 'd860) //43s 8×Ö X -Y 60¡ã
		begin
			x_speed <= -16'd04;
			y_speed <= 16'd07;
		end
		else if (cnt <= 'd880) //44s 8×Ö X 90¡ã
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd08;
		end
		else
		begin
			x_speed <= 16'd00;
			y_speed <= 16'd00;
			z_speed <= 16'd00;
		end
	end
	
	
	
endmodule    //dance_ctrl

