module dance_cmd(
	sys_clk_i,
	sys_rst_n_i,
	rx_data,
	rx_done,
	x_speed,
	y_speed,
	z_speed,
	dance_ack);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] rx_data;
	input rx_done;
	output [15:0] x_speed;
	output [15:0] y_speed;
	output [15:0] z_speed;
	output dance_ack;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] rx_data;
	wire rx_done;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	wire dance_ack;
	wire clk_div1_clk_o;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_str [3:0];
	reg clk_en;
	reg clr_en;
	
	always@(posedge sys_clk_i)
	if (rx_done) begin
		data_str[3] <= #1 rx_data;
		data_str[2] <= #1 data_str[3];
		data_str[1] <= #1 data_str[2];
		data_str[0] <= #1 data_str[1];
	end
	    
	reg r_rx_done;
	always@(posedge sys_clk_i)
		r_rx_done <= rx_done;
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		clk_en <= 1'b0;
		clr_en <= 1'b0;
	end
	else if (r_rx_done) begin
		if ((data_str[0] == 8'h55) && (data_str[1] == 8'hC5) && (data_str[3] == 8'hF0)) begin
			if (data_str[2] == 8'h01)
			begin
				clk_en <= 1'b1;
				clr_en <= 1'b0;
			end
			else if (data_str[2] == 8'h00)
			begin
				clk_en <= 1'b1;
				clr_en <= 1'b1;
			end
		end
		else begin
			clk_en <= clk_en;
			clr_en <= clr_en;
		end
	end
	else begin
		clk_en <= clk_en;
		clr_en <= clr_en;
	end
	
	
	//---Module instantiation---
	clk_div #(  1666650) clk_div1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.clk_en(clk_en),
		.clk_o(clk_div1_clk_o));

	dance_ctrl dance_ctrl2(
		.clk_i(clk_div1_clk_o),
		.sys_rst_n_i(sys_rst_n_i),
		.x_speed(x_speed),
		.y_speed(y_speed),
		.z_speed(z_speed),
		.dance_ack(dance_ack),
		.clr_en(clr_en));

endmodule    //dance_cmd

