module fsm_wheel(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	wheel,
	wheel_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [1:0] wheel;
	output wheel_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [1:0] wheel;
	reg wheel_ok;

	//----Code starts here: integrated by Robei-----
	localparam
		CHECK_w  = 7'b000_0001,
		CHECK_h  = 7'b000_0010,
		CHECK_e1 = 7'b000_0100,
		CHECK_e2 = 7'b000_1000,
		CHECK_l  = 7'b001_0000,
		CHECK_plus = 7'b010_0000,
		CHECK_num = 7'b100_0000;
	wire reset = ~sys_rst_n_i;
	reg [6:0] state;
	    
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		wheel_ok <= 1'b0;
		wheel <= 2'd00;
		state <= CHECK_w;
	end
	else begin
		case (state)
			CHECK_w:
				begin
					wheel_ok <= 1'b0;
					if (data_valid && data_in == "w")
						state <= CHECK_h;
					else
						state <= CHECK_w;
				end
			CHECK_h:
				if (data_valid && data_in == "h")
	 				state <= CHECK_e1;
				else if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
					state <= CHECK_w;
				else
					state <= CHECK_h;
			CHECK_e1:
				if (data_valid && data_in == "e")
					state <= CHECK_e2;
				else if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
					state <= CHECK_w;
				else
					state <= CHECK_e1;
			CHECK_e2:
				if (data_valid && data_in == "e")
					state <= CHECK_l;
				else if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
					state <= CHECK_w;
				else
					state <= CHECK_e2;
			CHECK_l:
				if (data_valid && data_in == "l")
					state <= CHECK_plus;
				else if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
					state <= CHECK_w;
				else
					state <= CHECK_l;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
					state <= CHECK_w;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "w")
					state <= CHECK_h;
				else if (data_valid)
				begin
					state <= CHECK_w;
					if (data_in>="0" && data_in <= "2") begin
						wheel_ok <= 1'b1;
						wheel <= data_in-"0";
					end
					else
						wheel_ok <= 1'b0;
					end
				else
					state <= CHECK_num;
			default:state <= CHECK_w;
		endcase
	end
endmodule    //fsm_wheel

