module Mcknum_wheel_calculate(
	sys_clk_i,
	sys_rst_n_i,
	McKnum_cal_en,
	x_speed,
	y_speed,
	z_speed,
	M1_speed_out,
	M2_speed_out,
	M3_speed_out,
	M4_speed_out,
	A_length_mm,
	B_length_mm);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input McKnum_cal_en;
	input [15:0] x_speed;
	input [15:0] y_speed;
	input [15:0] z_speed;
	output [15:0] M1_speed_out;
	output [15:0] M2_speed_out;
	output [15:0] M3_speed_out;
	output [15:0] M4_speed_out;
	input [15:0] A_length_mm;
	input [15:0] B_length_mm;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire McKnum_cal_en;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	reg [15:0] M1_speed_out;
	reg [15:0] M2_speed_out;
	reg [15:0] M3_speed_out;
	reg [15:0] M4_speed_out;
	wire [15:0] A_length_mm;
	wire [15:0] B_length_mm;

	//----Code starts here: integrated by Robei-----
	//单位具体再调
	 parameter  Car_x = 250; //底盘x轴上两轮中心的间距
	 parameter  Car_y = 200; //底盘y轴上两轮中心的间距
	
	/**
	  * @作用：逆向运动学解析，底盘三轴速度-->轮子速度
	  * @输入：机器人三轴速度 
	  * @输出：机器人四个轮子速度输出
	  */
	//reg signed[14:0]M1_speed_out;
	//reg signed[14:0]M2_speed_out;
	//reg signed[14:0]M3_speed_out;
	//reg signed[14:0]M4_speed_out;
	
	reg signed[15:0] x_speed_tem;
	reg signed[15:0] y_speed_tem;
	reg signed[15:0] z_speed_tem;
	
	reg [15:0] z_speed_r;
	reg [15:0] z_speed_o;
	
	
	always @(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0) begin
		x_speed_tem<=0;
		y_speed_tem<=0;
		z_speed_tem<=0;
		z_speed_r <= 0;
		z_speed_o <= 0;
		end
	else 
		if(McKnum_cal_en == 1)begin
		x_speed_tem <= x_speed;
		y_speed_tem <= y_speed;
		if (z_speed[15] == 1'b0)
			z_speed_tem <= ((z_speed * (A_length_mm+B_length_mm) * 2)>>7) + ((z_speed * (A_length_mm+B_length_mm) * 2)>>9);
		else if (z_speed[15] == 1'b1) begin
			z_speed_r <= (~z_speed + 1);
			z_speed_o <= ((z_speed_r * (A_length_mm+B_length_mm) * 2)>>7) + ((z_speed_r * (A_length_mm+B_length_mm) * 2)>>9);
			z_speed_tem <= (~z_speed_o + 1);
		end
	end
	
	
	//pwm_out
	always @(posedge sys_clk_i or negedge sys_rst_n_i)
	if(sys_rst_n_i == 0) begin
		  M1_speed_out <= 0;
		  M2_speed_out <= 0;
		  M3_speed_out <= 0;
		  M4_speed_out <= 0;
		end
	else 
		if(McKnum_cal_en == 1)begin
		  M1_speed_out <= x_speed_tem + y_speed_tem + z_speed_tem;
		  M2_speed_out <= x_speed_tem - y_speed_tem - z_speed_tem;
		  M3_speed_out <= x_speed_tem - y_speed_tem + z_speed_tem;
		  M4_speed_out <= x_speed_tem + y_speed_tem - z_speed_tem;
	end
	
	
	//负数的表示形式为补码，可以reg dir; dir = 符号位
	//除去符号位的为真值
	
	
endmodule    //Mcknum_wheel_calculate

