module motion(
	sys_clk_i,
	sys_rst_n_i,
	clk,
	X,
	Y,
	theta,
	pulsea,
	pulseb,
	pulsec,
	pulsed,
	pulsee,
	pulsef,
	observe_en,
	motion_en,
	pack_en,
	catch_en,
	adjust,
	theta_ad,
	put_en);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input clk;
	input [15:0] X;
	input [15:0] Y;
	input [31:0] theta;
	output [31:0] pulsea;
	output [31:0] pulseb;
	output [31:0] pulsec;
	output [31:0] pulsed;
	output [31:0] pulsee;
	output [31:0] pulsef;
	input [1:0] observe_en;
	input motion_en;
	input pack_en;
	input catch_en;
	input [7:0] adjust;
	input [7:0] theta_ad;
	input [1:0] put_en;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire clk;
	wire [15:0] X;
	wire [15:0] Y;
	wire [31:0] theta;
	reg [31:0] pulsea;
	reg [31:0] pulseb;
	reg [31:0] pulsec;
	reg [31:0] pulsed;
	reg [31:0] pulsee;
	reg [31:0] pulsef;
	wire [1:0] observe_en;
	wire motion_en;
	wire pack_en;
	wire catch_en;
	wire [7:0] adjust;
	wire [7:0] theta_ad;
	wire [1:0] put_en;

	//----Code starts here: integrated by Robei-----
	reg [31:0] pulsea_o;
	reg [31:0] pulseb_o;
	reg [31:0] pulsec_o;
	reg [31:0] pulsed_o;
	reg [31:0] pulsee_o;
	//reg [31:0] pulsef_o;
	
	reg cordic_req1;
	reg cordic_req2;
	reg cordic_req3;
	reg cordic_req4;
	reg cordic_req5;
	reg cordic_req6;
	reg start;
	wire cordic_ack1;
	wire cordic_ack2;
	wire cordic_ack3;
	wire cordic_ack4;
	wire cordic_ack5;
	wire cordic_ack6;
	wire div_ack;
	
	wire [31:0] theta1;
	reg [31:0] theta2;
	wire [31:0] theta2_1;
	wire [31:0] theta2_2;
	wire [31:0] theta3;
	reg [31:0] theta4;
	wire [15:0] arm;
	
	//reg [31:0] theta2_past;
	//reg [31:0] theta4_past;
	
	wire [31:0] cos_theta;
	wire [31:0] sin_theta;
	wire [31:0] cos_theta3;
	wire [31:0] sin_theta3;
	reg [31:0] dividend;
	reg [15:0] divisor;
	wire [31:0] quotient;
	reg [15:0] X1;
	reg [15:0] Y1;
	reg [15:0] X2;
	reg [15:0] Y2;
	
	reg wait_en;
	
	reg [31:0] pulsea_ad;
	reg [31:0] pulseb_ad;
	reg [31:0] pulsec_ad;
	reg [31:0] pulsed_ad;
	
	localparam
		IDLE       = 8'b00000001,
		ARM       = 8'b00000010,
		DIV         = 8'b00000100,
		THETA3 = 8'b00001000,
		SINCOS = 8'b00010000,
		THETA2 = 8'b00100000,
		THETA4 = 8'b01000000,
		WAIT      = 8'b10000000;
	
	reg [7:0] state;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
	begin
		state <= IDLE;
		pulsea_o <= 32'd8323072;  // 127бу * 2^16
		pulseb_o <= 32'd3276800;  // 50бу * 2^16
		pulsec_o <= 32'd0;              // 0бу * 2^16
		pulsed_o <= 32'd10485760;// 160бу * 2^16
		pulsee_o <= 32'd8716288;  // 133бу * 2^16
	//	pulsee_o <= 32'd8519680;  // 130бу * 2^16
	//	pulsef_o <= 32'd0;               // 0бу * 2^16
	
		cordic_req1 <= 1'b0;
		cordic_req2 <= 1'b0;
		cordic_req3 <= 1'b0;
		cordic_req4 <= 1'b0;
		cordic_req5 <= 1'b0;
		cordic_req6 <= 1'b0;
		start <= 1'b0;
		theta2 <= 32'd0;
		theta4 <= 32'd0;
	//	theta2_past <= 32'd0;
	//	theta4_past <= 32'd0;
		dividend <= 16'd0;
		divisor <= 16'd0;
		X1 <= 16'd0;
		Y1 <= 16'd0;
		X2 <= 16'd0;
		Y2 <= 16'd0;
	
		wait_en <= 1'b0;
	end
	else if (observe_en != 2'b00)
	begin
		state <= IDLE;
		if (observe_en == 2'b01)  //╫є
			pulsea_o <= 32'd14221312;  // (127бу+90бу) * 2^16
		else if (observe_en == 2'b10)  //╟░
			pulsea_o <= 32'd8323072;  // (127бу) * 2^16
		else if (observe_en == 2'b11)  //╙╥
			pulsea_o <= 32'd2424832;  // (127бу-90бу) * 2^16
		pulseb_o <= 32'd5898240;  // (45бу+45бу) * 2^16
		pulsec_o <= 32'd10158080;  // (110бу+45бу) * 2^16
		pulsed_o <= 32'd7864320;  // 120бу * 2^16
		wait_en <= 1'b0;
	end
	else if (motion_en)
	begin
		case (state)
		IDLE:
			begin
				cordic_req1 <= 1'b1;
				state <= ARM;
				wait_en <= 1'b0;
			end
		ARM:
			begin
				if (cordic_ack1 == 1'b1)
				begin
					cordic_req1 <= 1'b0;
					cordic_req2 <= 1'b1;
					state <= DIV;
				end
				else
					state <= ARM;
			end
		DIV:
			begin
				if (cordic_ack2 == 1'b1)
				begin
					cordic_req2 <= 1'b0;
					dividend <= (arm-'d78*(cos_theta>>>10))**2 +  ('d78*(sin_theta>>>10)-'d3789)**2 - 'd7088374 - 'd6166282;
					//dividend <= (arm-'d5*(cos_theta>>>6))**2 +  ('d5*(sin_theta>>>6)-'d3789)**2 - 'd7088374 - 'd6166282;
					divisor <= 16'd51651;
					start <= 1'b1;
					state <= THETA3;
				end
				else
					state <= DIV;
			end
		THETA3:
			begin
				if (div_ack == 1'b1)
				begin
					start <= 1'b0;
					cordic_req3 <= 1'b1;
					state <= SINCOS;
				end
				else
					state <= THETA3;
			end
		SINCOS:
			begin
				if (cordic_ack3 == 1'b1)
				begin
					cordic_req3 <= 1'b0;
					cordic_req4 <= 1'b1;
					state <= THETA2;
				end
				else
					state <= SINCOS;
			end
		THETA2:
			begin
				if (cordic_ack4 == 1'b1)
				begin
					cordic_req4 <= 1'b0;
					Y1 <= 10 * (sin_theta3 >>> 8);
					X1 <= 'd2662 + 'd10 * (cos_theta3 >>> 8);
					Y2 <= 'd3789 - 'd19 * (sin_theta >>> 8);
					X2 <= arm - 'd19 * (cos_theta >>> 8);
					cordic_req5 <= 1'b1;
					cordic_req6 <= 1'b1;
					state <= THETA4;
				end
				else
					state <= THETA2;
			end
		THETA4:
			begin
				if ((cordic_ack5 == 1'b1) && (cordic_ack6 == 1'b1))
				begin
					cordic_req5 <= 1'b0;
					cordic_req6 <= 1'b0;
					theta2 <= theta2_1 - theta2_2;
					theta4 <= theta + theta2 - theta3;
					wait_en <= 1'b1;
					//if ((theta2_past != theta2) && (theta4_past != theta4))
					if ((theta2 != 32'd0) && (theta4 != 32'd0))
					begin
						//wait_en <= 1'b1;
						state <= WAIT;
					end
				end
				else
				begin
					state <= THETA4;
					theta2 <= 32'd0;
					theta4 <= 32'd0;
					//theta2_past <= theta2;
					//theta4_past <= theta2;
				end
			end
		WAIT:
			begin
				state <= WAIT;
			end
		default:
				state <= IDLE;
		endcase
	end
	else if (pack_en)
	begin
		state <= IDLE;
		pulsea_o <= 32'd8323072;  // 127бу * 2^16
		pulseb_o <= 32'd3276800;  // 50бу * 2^16
		pulsec_o <= 32'd0;              // 0бу * 2^16
		pulsed_o <= 32'd10485760;// 160бу * 2^16
		wait_en <= 1'b0;
	end
	else if (put_en != 2'b00)
	begin
		state <= IDLE;
		if (put_en == 2'b01) //╫є
			pulsea_o <= 32'd6356992;  // 97бу * 2^16
		else if (put_en == 2'b10) //╓╨
			pulsea_o <= 32'd8323072;  // 127бу * 2^16
		else if (put_en == 2'b11) //╙╥
			pulsea_o <= 32'd10289152;  // 157бу * 2^16
	//	pulseb_o <= 32'd2949120;   // 45бу * 2^16
	//	pulsec_o <= 32'd10158080; // 155бу * 2^16
	//	pulsed_o <= 32'd7864320;   // 120бу * 2^16
	
		pulseb_o <= 32'd4587520;   // 70бу * 2^16
		pulsec_o <= 32'd12451840; // 190бу * 2^16
		pulsed_o <= 32'd7864320;   // 120бу * 2^16
		wait_en <= 1'b0;
	end
	else
	begin
		state <= state;
		pulsea_o <= pulsea_o;  // 127бу * 2^16
		pulseb_o <= pulseb_o;  // 50бу * 2^16
		pulsec_o <= pulsec_o;              // 0бу * 2^16
		pulsed_o <= pulsed_o;// 160бу * 2^16
		pulsee_o <= pulsee_o;  // 130бу * 2^16
		//pulsef_o <= pulsef_o;               // 0бу * 2^16
	
		cordic_req1 <= cordic_req1;
		cordic_req2 <= cordic_req2;
		cordic_req3 <= cordic_req3;
		cordic_req4 <= cordic_req4;
		cordic_req5 <= cordic_req5;
		cordic_req6 <= cordic_req6;
		start <= start;
		theta2 <= theta2;
		theta4 <= theta4;
	//	theta2_past <= theta2_past;
	//	theta4_past <= theta4_past;
		dividend <= dividend;
		divisor <= divisor;
		X1 <= X1;
		Y1 <= Y1;
		X2 <= X2;
		Y2 <= Y2;
		
		wait_en <= 1'b0;
	end
	
	reg [2:0] state2;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
	begin
	//	pulsee <= pulsee_o;
	//	pulsed <= pulsed_o;
	//	pulsec <= pulsec_o;
	//	pulseb <= pulseb_o;
	//	pulsea <= pulsea_o;
		pulsea <= 32'd8323072;  // 127бу * 2^16
		pulseb <= 32'd3276800;  // 50бу * 2^16
		pulsec <= 32'd0;              // 0бу * 2^16
		pulsed <= 32'd10485760;// 160бу * 2^16
		pulsee <= 32'd8716288;  // 133бу * 2^16
	//	pulsee <= 32'd8519680; 
	end
	else if (state  == IDLE)
	begin
		case(state2)
		1:
			begin
			if (observe_en)
				pulsea <= pulsea_o;
			else if ((pack_en) || (put_en))
				pulsed <= pulsed_o;
			end
		2:
			begin
			if (observe_en)
				pulseb <= pulseb_o;
			else if ((pack_en) || (put_en))
				pulsec <= pulsec_o;
			end
		3:
			begin
			if (observe_en)
				pulsec <= pulsec_o;
			else if ((pack_en) || (put_en))
				pulseb <= pulseb_o;
			end
		4:
			begin	
			if (observe_en)
				pulsed <= pulsed_o;
			else if ((pack_en) || (put_en))
				pulsea <= pulsea_o;
			end
		default:
		begin
			pulsea <= pulsea + pulsea_ad;
			pulseb <= pulseb + pulseb_ad;
			pulsec <= pulsec + pulsec_ad;
			pulsed <= pulsed + pulsed_ad;
		end
		endcase
	end
	/*
	else if (state  == WAIT)
	begin
		case(state2)
		1:
			pulsea <= 'd8323072 + theta1;  //172 + theta1
		2:
			pulseb <= 'd2949120 + theta2;  //45 + theta2
		3:
			pulsec <= 'd7864320 + theta3;  //120 + theta3
		4:
			pulsed <= 'd7864320 + theta4;  //120 + theta4
		default:
		begin
			pulsea <= pulsea + pulsea_ad;
			pulseb <= pulseb + pulseb_ad;
			pulsec <= pulsec + pulsec_ad;
			pulsed <= pulsed + pulsed_ad;
		end
		endcase
	end
	*/
	else
	begin
		pulsea <= pulsea;
		pulseb <= pulseb;
		pulsec <= pulsec;
		pulsed <= pulsed;
		pulsee <= pulsee;
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		pulsef <= 32'd0;
	else
	begin
		case (catch_en)
		1:
			pulsef<= 32'd4587520; //70
		0:
			pulsef <= 32'd0;
		default:
			pulsef <= pulsef;
		endcase
	end
	
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
	begin
		pulsea_ad <= 32'd0;
		pulseb_ad <= 32'd0;
		pulsec_ad <= 32'd0;
		pulsed_ad <= 32'd0;
	end
	//else if (state == WAIT)
	else if (state == IDLE)
	begin
		if (adjust != 8'd0)
			case (adjust)
				8'd1:
					pulsea_ad <= (theta_ad <<< 15); //+ж╚/2
				8'd2:
					pulsea_ad <= -(theta_ad <<< 15);  //-ж╚/2
				8'd4:
					pulseb_ad <= (theta_ad <<< 15); //+ж╚/2
				8'd8:
					pulseb_ad <= -(theta_ad <<< 15);  //-ж╚/2
				8'd16:
					pulsec_ad <= (theta_ad <<< 15); //+ж╚/2
				8'd32:
					pulsec_ad <= -(theta_ad <<< 15);  //-ж╚/2
				8'd64:
					pulsed_ad <= (theta_ad <<< 15); //+ж╚/2
				8'd128:
					pulsed_ad <= -(theta_ad <<< 15);  //-ж╚/2
				default:
				begin
					pulsea_ad <= pulsea_ad;
					pulseb_ad <= pulseb_ad;
					pulsec_ad <= pulsec_ad;
					pulsed_ad <= pulsed_ad;
				end
			endcase
		else
		begin
	/*
			pulsea_ad <= pulsea_ad;
			pulseb_ad <= pulseb_ad;
			pulsec_ad <= pulsec_ad;
			pulsed_ad <= pulsed_ad;
	*/
			pulsea_ad <= 32'd0;
			pulseb_ad <= 32'd0;
			pulsec_ad <= 32'd0;
			pulsed_ad <= 32'd0;
	
		end
	end
	//else if (state == IDLE)
	else if (state == WAIT)
	begin
		pulsea_ad <= 32'd0;
		pulseb_ad <= 32'd0;
		pulsec_ad <= 32'd0;
		pulsed_ad <= 32'd0;
	end
	else
	begin
		pulsea_ad <= pulsea_ad;
		pulseb_ad <= pulseb_ad;
		pulsec_ad <= pulsec_ad;
		pulsed_ad <= pulsed_ad;
	end
	
	reg observe_en_r;
	reg motion_en_r;
	reg pack_en_r;
	reg wait_r;
	reg put_en_r;
	
	
	always @ (posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
	begin
		observe_en_r <= 1'b0;
		motion_en_r <= 1'b0;
		pack_en_r <= 1'b0;
		wait_r <= 1'b0;
		put_en_r <= 1'b0;
	end
	else
	begin
		observe_en_r <= (observe_en != 2'b00) ? 1'b1 : 1'b0;
		motion_en_r <= motion_en;
		pack_en_r <= pack_en;
		wait_r <= wait_en;
		put_en_r <= (put_en != 2'b00) ? 1'b1 : 1'b0;
	end
	
	reg cnt_en;
	
	always @ (posedge clk or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
	begin
		state2 <= 3'd0;
	end
	else if (cnt_en == 1'b1)
	begin
		state2 <= state2 + 1'b1;
		if (state2 == 3'd5)
		begin
			state2 <= 3'd0;
		end
	end
	else 
		state2 <= 3'd0;
	
	always @ (posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		cnt_en <= 1'b0;
	else if (((observe_en != 2'd0) & ~observe_en_r) ||  (pack_en & ~pack_en_r) || (wait_en & ~wait_r) || ((put_en != 2'd0) & ~put_en_r))
	begin
		cnt_en <= 1'b1;
	end
	else if (state2 == 3'd5)
	begin
		cnt_en <= 1'b0;
	end
	else
		cnt_en <= cnt_en;
	//---Module instantiation---
	cordic_arctan cordic_arctan1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req1),
		.X(X),
		.Y(Y),
		.cordic_ack(cordic_ack1),
		.amplitude(arm),
		.theta(theta1));

	cordic_sincos cordic_sincos2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req2),
		.theta(theta),
		.cordic_ack(cordic_ack2),
		.cos(cos_theta),
		.sin(sin_theta));

	divider #(32,16) divider3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.start(start),
		.dividend(dividend),
		.divisor(divisor),
		.quotient_vld(div_ack),
		.quotient(quotient));

	cordic_arccos cordic_arccos4(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req3),
		.W(quotient),
		.cordic_ack(cordic_ack3),
		.theta(theta3));

	cordic_sincos cordic_sincos5(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req4),
		.theta(theta3),
		.cordic_ack(cordic_ack4),
		.cos(cos_theta3),
		.sin(sin_theta3));

	cordic_arctan cordic_arctan6(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req5),
		.X(X1),
		.Y(Y1),
		.cordic_ack(cordic_ack5),
		.theta(theta2_1));

	cordic_arctan cordic_arctan7(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.cordic_req(cordic_req6),
		.X(X2),
		.Y(Y2),
		.cordic_ack(cordic_ack6),
		.theta(theta2_2));

endmodule    //motion

