module wheel_ctrl(
	sys_clk_i,
	sys_rst_n_i,
	x_speed,
	y_speed,
	z_speed,
	motor_encoder_A_1,
	motor_encoder_B_1,
	motor_encoder_A_2,
	motor_encoder_B_2,
	motor_encoder_A_3,
	motor_encoder_B_3,
	motor_encoder_A_4,
	motor_encoder_B_4,
	M1_in1,
	M1_in2,
	M1_pwm,
	M2_in1,
	M2_in2,
	M2_pwm,
	M3_in1,
	M3_in2,
	M3_pwm,
	M4_in1,
	M4_in2,
	M4_pwm,
	wheel,
	pulse_data,
	a_length,
	b_length);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [15:0] x_speed;
	input [15:0] y_speed;
	input [15:0] z_speed;
	input motor_encoder_A_1;
	input motor_encoder_B_1;
	input motor_encoder_A_2;
	input motor_encoder_B_2;
	input motor_encoder_A_3;
	input motor_encoder_B_3;
	input motor_encoder_A_4;
	input motor_encoder_B_4;
	output M1_in1;
	output M1_in2;
	output M1_pwm;
	output M2_in1;
	output M2_in2;
	output M2_pwm;
	output M3_in1;
	output M3_in2;
	output M3_pwm;
	output M4_in1;
	output M4_in2;
	output M4_pwm;
	input [1:0] wheel;
	input [31:0] pulse_data;
	input [15:0] a_length;
	input [15:0] b_length;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	wire motor_encoder_A_1;
	wire motor_encoder_B_1;
	wire motor_encoder_A_2;
	wire motor_encoder_B_2;
	wire motor_encoder_A_3;
	wire motor_encoder_B_3;
	wire motor_encoder_A_4;
	wire motor_encoder_B_4;
	wire M1_in1;
	wire M1_in2;
	wire M1_pwm;
	wire M2_in1;
	wire M2_in2;
	wire M2_pwm;
	wire M3_in1;
	wire M3_in2;
	wire M3_pwm;
	wire M4_in1;
	wire M4_in2;
	wire M4_pwm;
	wire [1:0] wheel;
	wire [31:0] pulse_data;
	wire [15:0] a_length;
	wire [15:0] b_length;

	//----Code starts here: integrated by Robei-----
	reg M1_spin_dir;
	reg [15:0] M1_rpm_set;
	reg M2_spin_dir;
	reg [15:0] M2_rpm_set;
	reg M3_spin_dir;
	reg [15:0] M3_rpm_set;
	reg M4_spin_dir;
	reg [15:0] M4_rpm_set;
	wire Mcknum_en;
	wire direction_four_en;
	wire direction_three_en;
	
	assign Mcknum_en = (wheel == 0) ? 1'b1 : 1'b0;
	assign direction_four_en = (wheel == 1) ? 1'b1 : 1'b0;
	assign direction_three_en = (wheel == 2) ? 1'b1 : 1'b0;
	
	wire [15:0] Mck_M1_speed_out;
	wire [15:0] Mck_M2_speed_out;
	wire [15:0] Mck_M3_speed_out;
	wire [15:0] Mck_M4_speed_out;
	
	wire [15:0] F_Dir_M1_speed_out;
	wire [15:0] F_Dir_M2_speed_out;
	wire [15:0] F_Dir_M3_speed_out;
	wire [15:0] F_Dir_M4_speed_out;
	
	wire [15:0] T_Dir_M1_speed_out;
	wire [15:0] T_Dir_M2_speed_out;
	wire [15:0] T_Dir_M3_speed_out;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		M1_spin_dir <= 1'b0;
		M1_rpm_set <= 16'd0;
	end
	else begin
		if (Mcknum_en) begin
			if (Mck_M1_speed_out[15] == 'b0) begin
				M1_spin_dir <= 1'b0;
				M1_rpm_set <= Mck_M1_speed_out;
			end
			else if (Mck_M1_speed_out[15] == 'b1) begin
				M1_spin_dir <= 1'b1;
				M1_rpm_set <= (~Mck_M1_speed_out + 1);
			end
		end
		else if (direction_four_en) begin
			if (F_Dir_M1_speed_out[15] == 'b0) begin
				M1_spin_dir <= 1'b0;
				M1_rpm_set <= F_Dir_M1_speed_out;
			end
			else if (F_Dir_M1_speed_out[15] == 'b1) begin
				M1_spin_dir <= 1'b1;
				M1_rpm_set <= (~F_Dir_M1_speed_out + 1);
			end
		end
		else if (direction_three_en) begin
			if (T_Dir_M1_speed_out[15] == 'b0) begin
				M1_spin_dir <= 1'b0;
				M1_rpm_set <= T_Dir_M1_speed_out;
			end
			else if (T_Dir_M1_speed_out[15] == 'b1) begin
				M1_spin_dir <= 1'b1;
				M1_rpm_set <= (~T_Dir_M1_speed_out + 1);
			end
		end
		else begin
			M1_spin_dir <= M1_spin_dir;
			M1_rpm_set <= M1_rpm_set;
		end
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		M2_spin_dir <= 1'b0;
		M2_rpm_set <= 16'd0;
	end
	else begin
		if (Mcknum_en) begin
			if (Mck_M2_speed_out[15] == 'b0) begin
				M2_spin_dir <= 1'b0;
				M2_rpm_set <= Mck_M2_speed_out;
			end
			else if (Mck_M2_speed_out[15] == 'b1) begin
				M2_spin_dir <= 1'b1;
				M2_rpm_set <= (~Mck_M2_speed_out + 1);
			end
		end
		else if (direction_four_en) begin
			if (F_Dir_M2_speed_out[15] == 'b0) begin
				M2_spin_dir <= 1'b0;
				M2_rpm_set <= F_Dir_M2_speed_out;
			end
			else if (F_Dir_M2_speed_out[15] == 'b1) begin
				M2_spin_dir <= 1'b1;
				M2_rpm_set <= (~F_Dir_M2_speed_out + 1);
			end
		end
		else if (direction_three_en) begin
			if (T_Dir_M2_speed_out[15] == 'b0) begin
				M2_spin_dir <= 1'b0;
				M2_rpm_set <= T_Dir_M2_speed_out;
			end
			else if (T_Dir_M2_speed_out[15] == 'b1) begin
				M2_spin_dir <= 1'b1;
				M2_rpm_set <= (~T_Dir_M2_speed_out + 1);
			end
		end
		else begin
			M2_spin_dir <= M2_spin_dir;
			M2_rpm_set <= M2_rpm_set;
		end
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		M3_spin_dir <= 1'b0;
		M3_rpm_set <= 16'd0;
	end
	else begin
		if (Mcknum_en) begin
			if (Mck_M3_speed_out[15] == 'b0) begin
				M3_spin_dir <= 1'b0;
				M3_rpm_set <= Mck_M3_speed_out;
			end
			else if (Mck_M3_speed_out[15] == 'b1) begin
				M3_spin_dir <= 1'b1;
				M3_rpm_set <= (~Mck_M3_speed_out + 1);
			end
		end
		else if (direction_four_en) begin
			if (F_Dir_M3_speed_out[15] == 'b0) begin
				M3_spin_dir <= 1'b0;
				M3_rpm_set <= F_Dir_M3_speed_out;
			end
			else if (F_Dir_M3_speed_out[15] == 'b1) begin
				M3_spin_dir <= 1'b1;
				M3_rpm_set <= (~F_Dir_M3_speed_out + 1);
			end
		end
		else if (direction_three_en) begin
			if (T_Dir_M3_speed_out[15] == 'b0) begin
				M3_spin_dir <= 1'b0;
				M3_rpm_set <= T_Dir_M3_speed_out;
			end
			else if (T_Dir_M3_speed_out[15] == 'b1) begin
				M3_spin_dir <= 1'b1;
				M3_rpm_set <= (~T_Dir_M3_speed_out + 1);
			end
		end
		else begin
			M3_spin_dir <= M3_spin_dir;
			M3_rpm_set <= M3_rpm_set;
		end
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		M4_spin_dir <= 1'b0;
		M4_rpm_set <= 16'd0;
	end
	else begin
		if (Mcknum_en) begin
			if (Mck_M4_speed_out[15] == 'b0) begin
				M4_spin_dir <= 1'b0;
				M4_rpm_set <= Mck_M4_speed_out;
			end
			else if (Mck_M4_speed_out[15] == 'b1) begin
				M4_spin_dir <= 1'b1;
				M4_rpm_set <= (~Mck_M4_speed_out + 1);
			end
		end
		else if (direction_four_en) begin
			if (F_Dir_M4_speed_out[15] == 'b0) begin
				M4_spin_dir <= 1'b0;
				M4_rpm_set <= F_Dir_M4_speed_out;
			end
			else if (F_Dir_M4_speed_out[15] == 'b1) begin
				M4_spin_dir <= 1'b1;
				M4_rpm_set <= (~F_Dir_M4_speed_out + 1);
			end
		end
		else if (direction_three_en) begin
			M4_spin_dir <= 1'b0;
			M4_rpm_set <= 16'd0;
		end
		else begin
			M4_spin_dir <= M4_spin_dir;
			M4_rpm_set <= M4_rpm_set;
		end
	end
	//---Module instantiation---
	dc_motor_driver_top dc_motor_driver_top1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir(M1_spin_dir),
		.motor_rpm_set(M1_rpm_set),
		.motor_encoder_A_i(motor_encoder_A_1),
		.motor_encoder_B_i(motor_encoder_B_1),
		.pulse_data(pulse_data),
		.motor_ain1_o(M1_in1),
		.motor_ain2_o(M1_in2),
		.motor_pwm_o(M1_pwm));

	dc_motor_driver_top dc_motor_driver_top2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir(M2_spin_dir),
		.motor_rpm_set(M2_rpm_set),
		.motor_encoder_A_i(motor_encoder_A_2),
		.motor_encoder_B_i(motor_encoder_B_2),
		.pulse_data(pulse_data),
		.motor_ain1_o(M2_in1),
		.motor_ain2_o(M2_in2),
		.motor_pwm_o(M2_pwm));

	dc_motor_driver_top dc_motor_driver_top3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir(M3_spin_dir),
		.motor_rpm_set(M3_rpm_set),
		.motor_encoder_A_i(motor_encoder_A_3),
		.motor_encoder_B_i(motor_encoder_B_3),
		.pulse_data(pulse_data),
		.motor_ain1_o(M3_in1),
		.motor_ain2_o(M3_in2),
		.motor_pwm_o(M3_pwm));

	dc_motor_driver_top dc_motor_driver_top4(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir(M4_spin_dir),
		.motor_rpm_set(M4_rpm_set),
		.motor_encoder_A_i(motor_encoder_A_4),
		.motor_encoder_B_i(motor_encoder_B_4),
		.pulse_data(pulse_data),
		.motor_ain1_o(M4_in1),
		.motor_ain2_o(M4_in2),
		.motor_pwm_o(M4_pwm));

	Mcknum_wheel_calculate Mcknum_wheel_calculate5(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.McKnum_cal_en(Mcknum_en),
		.x_speed(x_speed),
		.y_speed(y_speed),
		.z_speed(z_speed),
		.M1_speed_out(Mck_M1_speed_out),
		.M2_speed_out(Mck_M2_speed_out),
		.M3_speed_out(Mck_M3_speed_out),
		.M4_speed_out(Mck_M4_speed_out),
		.A_length_mm(a_length),
		.B_length_mm(b_length));

	all_direction_wheel_four_calculate all_direction_wheel_four_calculate6(
		.M1_speed_out(F_Dir_M1_speed_out),
		.M2_speed_out(F_Dir_M2_speed_out),
		.M3_speed_out(F_Dir_M3_speed_out),
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.all_direction_wheel_en(direction_four_en),
		.x_speed(x_speed),
		.y_speed(y_speed),
		.z_speed(z_speed),
		.M4_speed_out(F_Dir_M4_speed_out),
		.A_length_mm(a_length),
		.B_length_mm(b_length));

	all_direction_wheel_three_calculate all_direction_wheel_three_calculate7(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.all_direction_wheel_en(direction_three_en),
		.x_speed(x_speed),
		.y_speed(y_speed),
		.z_speed(z_speed),
		.M1_speed_out(T_Dir_M1_speed_out),
		.M2_speed_out(T_Dir_M2_speed_out),
		.M3_speed_out(T_Dir_M3_speed_out));

endmodule    //wheel_ctrl

