/*传入X,Y，传出平方差和扩大2^16倍的角度角*/

module cordic_arctanh(
	sys_clk_i,
	sys_rst_n_i,
	cordic_req,
	X,
	Y,
	cordic_ack,
	amplitude,
	theta);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input cordic_req;
	input [15:0] X;
	input [15:0] Y;
	output cordic_ack;
	output [15:0] amplitude;
	output [31:0] theta;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire cordic_req;
	wire [15:0] X;
	wire [15:0] Y;
	wire cordic_ack;
	wire [15:0] amplitude;
	wire [31:0] theta;

	//----Code starts here: integrated by Robei-----
	`define rot0 32'd35999  //arctanh2^-1 * 2^16
	`define rot1 32'd16738  //arctanh2^-2 * 2^16
	`define rot2 32'd8235  //arctanh2^-3 * 2^16
	`define rot3 32'd4101  //arctanh2^-4 * 2^16
	`define rot4 32'd2048  //arctanh2^-5 * 2^16
	`define rot5 32'd1024  //arctanh2^-6 * 2^16
	`define rot6 32'd512  //arctanh2^-7 * 2^16
	`define rot7 32'd256  //arctanh2^-8 * 2^16
	`define rot8 32'd128  //arctanh2^-9 * 2^16
	`define rot9 32'd64  //arctanh2^-10 * 2^16
	`define rot10 32'd32  //arctanh2^-11 * 2^16
	`define rot11 32'd16  //arctanh2^-12 * 2^16
	`define rot12 32'd8  //arctanh2^-13 * 2^16
	`define rot13 32'd4  //arctanh2^-14 * 2^16
	`define rot14 32'd2  //arctanh2^-15 * 2^16
	`define rot15 32'd1  //arctanh2^-16 * 2^16
	
	
	reg signed[31:0]    Xn[16:0];
	reg signed[31:0]    Yn[16:0];
	reg signed[31:0]    Zn[16:0];
	reg[31:0]           rot[15:0];
	reg                 cal_delay[16:0];
	
	
	assign cordic_ack = cal_delay[16];
	assign theta      = Zn[16];
	//assign amplitude  = ((Xn[16] >>> 1) + (Xn[16]  >>> 3) +(Xn[16] >>> 4)) >>> 16;  //幅度，偏大0.8282倍，这里做了近似处理 ,然后缩小了2^16
	assign amplitude  = ((Xn[16]) + (Xn[16] >>> 3) + (Xn[16]  >>> 4) + (Xn[16]  >>> 6) + (Xn[16]  >>> 8)) >>> 16;
	
	always@(posedge sys_clk_i)
	begin
		rot[0] <= `rot0;
		rot[1] <= `rot1;
		rot[2] <= `rot2;
		rot[3] <= `rot3;
		rot[4] <= `rot4;
		rot[5] <= `rot5;
		rot[6] <= `rot6;
		rot[7] <= `rot7;
		rot[8] <= `rot8;
		rot[9] <= `rot9;
		rot[10] <= `rot10;
		rot[11] <= `rot11;
		rot[12] <= `rot12;
		rot[13] <= `rot13;
		rot[14] <= `rot14;
		rot[15] <= `rot15;
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	begin
		if( sys_rst_n_i == 1'b0)
			cal_delay[0] <= 1'b0;
		else
			cal_delay[0] <= cordic_req;
	end
	
	genvar j;
	generate
		for(j = 1 ;j < 17 ; j = j + 1)
		begin: loop
			always@(posedge sys_clk_i or negedge sys_rst_n_i)
			begin
				if( sys_rst_n_i == 1'b0)
					cal_delay[j] <= 1'b0;
				else
					cal_delay[j] <= cal_delay[j-1];
				end
		end
	endgenerate
	
	//将坐标挪到第一和四项限中
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	begin
		if( sys_rst_n_i == 1'b0)
		begin
			Xn[0] <= 'd0;
			Yn[0] <= 'd0;
			Zn[0] <= 'd0;
		end
		else if( cordic_req == 1'b1)
		begin
			if( X[15] == 1'b1 && Y[15] == 1'b1)
			begin
				Xn[0] <= -(X << 16);
				Yn[0] <= -(Y << 16);
			end
			else if( X[15] == 1'b1 && Y[15] == 1'b0)
			begin
				Xn[0] <= -(X << 16);
				Yn[0] <= -(Y << 16);
			end
			else
			begin
				Xn[0] <= X << 16;
				Yn[0] <= Y << 16;
			end
			Zn[0] <= 'd0;
		end
		else 
		begin
			Xn[0] <= Xn[0];
			Yn[0] <= Yn[0];
			Zn[0] <= Zn[0];
		end
	end
	
	
	//旋转
	genvar i;
	generate
		for( i = 1 ;i < 17 ;i = i+1)
		begin: loop2
			always@(posedge sys_clk_i or negedge sys_rst_n_i)
			begin
				if( sys_rst_n_i == 1'b0)
				begin
					Xn[i] <= 'd0;
					Yn[i] <= 'd0;
					Zn[i] <= 'd0;
				end
				else if( cal_delay[i -1] == 1'b1)
				begin
					if( Yn[i-1][31] == 1'b0)         //符号位
					begin
						Xn[i] <= Xn[i-1] - (Yn[i-1] >>> i);
						Yn[i] <= Yn[i-1] - (Xn[i-1] >>> i);
						Zn[i] <= Zn[i-1] + rot[i-1];
					end
					else
					begin
						Xn[i] <= Xn[i-1] + (Yn[i-1] >>> i);
						Yn[i] <= Yn[i-1] + (Xn[i-1] >>> i);
						Zn[i] <= Zn[i-1] - rot[i-1];
					end
					if (i % 3 == 1'b1 && i != 1'b1)
					begin
						if( Yn[i-1][31] == 1'b0)         //符号位
						begin
							Xn[i] <= Xn[i-1] - (Yn[i-1] >>> i);
							Yn[i] <= Yn[i-1] - (Xn[i-1] >>> i);
							Zn[i] <= Zn[i-1] + rot[i-1];
						end
						else
						begin
							Xn[i] <= Xn[i-1] + (Yn[i-1] >>> i);
							Yn[i] <= Yn[i-1] + (Xn[i-1] >>> i);
							Zn[i] <= Zn[i-1] - rot[i-1];
						end
					end
				end
				else
				begin
					Xn[i] <= Xn[i];
					Yn[i] <= Yn[i];
					Zn[i] <= Zn[i];
				end
			end
		end
	endgenerate
	
	
endmodule    //cordic_arctanh

