/*传入W(已经扩大了256倍)，传出扩大2^16倍的角度角*/

module cordic_arccos(
	sys_clk_i,
	sys_rst_n_i,
	cordic_req,
	W,
	cordic_ack,
	theta);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input cordic_req;
	input [31:0] W;
	output cordic_ack;
	output [31:0] theta;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire cordic_req;
	wire [31:0] W;
	wire cordic_ack;
	wire [31:0] theta;
	wire [15:0] cordic_arctanh1_amplitude;
	wire cordic_arctanh1_cordic_ack;

	//----Code starts here: integrated by Robei-----
	wire [15:0] W_L;
	assign W_L = W[15:0];
	//---Module instantiation---
	cordic_arctanh cordic_arctanh1(
		.cordic_req(cordic_req),
		.X(16'd256),
		.Y(W_L),
		.cordic_ack(cordic_arctanh1_cordic_ack),
		.amplitude(cordic_arctanh1_amplitude),
		.theta( ),
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i));

	cordic_arctan cordic_arctan2(
		.cordic_req(cordic_arctanh1_cordic_ack),
		.X(W_L),
		.Y(cordic_arctanh1_amplitude),
		.cordic_ack(cordic_ack),
		.amplitude( ),
		.theta(theta),
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i));

endmodule    //cordic_arccos

