module multiplier_8bit(
	sys_clk_i,
	sys_rst_n_i,
	din_en,
	din0,
	din1,
	dout_en,
	dout);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input din_en;
	input [7:0] din0;
	input [7:0] din1;
	output dout_en;
	output [15:0] dout;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire din_en;
	wire [7:0] din0;
	wire [7:0] din1;
	reg dout_en;
	reg [15:0] dout;

	//----Code starts here: integrated by Robei-----
	parameter DATA_NUM = 8;
	reg [15:0] sum;
	reg [7:0] cnt;
	
	wire [15:0] data0;
	wire [15:0] data1;
	wire [15:0] data2;
	wire [15:0] data3;
	wire [15:0] data4;
	wire [15:0] data5;
	wire [15:0] data6;
	wire [15:0] data7;
	
	assign data0 = din1[0] ? {8'h0,din0} : 'd0;
	assign data1 = din1[1] ? {7'h0,din0,1'h0} : 'd0;
	assign data2 = din1[2] ? {6'h0,din0,2'h0} : 'd0;
	assign data3 = din1[3] ? {5'h0,din0,3'h0} : 'd0;
	assign data4 = din1[4] ? {4'h0,din0,4'h0} : 'd0;
	assign data5 = din1[5] ? {3'h0,din0,5'h0} : 'd0;
	assign data6 = din1[6] ? {2'h0,din0,6'h0} : 'd0;
	assign data7 = din1[7] ? {1'h0,din0,7'h0} : 'd0;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		cnt <= DATA_NUM + 1;
	else if (din_en)
		cnt <= 8'h0;
	else if (cnt == (DATA_NUM + 1))
		cnt <= cnt;
	else
		cnt <= cnt + 8'h1;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		sum <= 'h0;
	else if (din_en)
		sum <= 'h0;
	else begin
		case (cnt)
			8'd0:sum <= sum + data0;
			8'd1:sum <= sum + data1;
			8'd2:sum <= sum + data2;
			8'd3:sum <= sum + data3;
			8'd4:sum <= sum + data4;
			8'd5:sum <= sum + data5;
			8'd6:sum <= sum + data6;
			8'd7:sum <= sum + data7;
			default: sum <= sum;
		endcase
	end
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		dout_en <= 'h0;
	else if (cnt == DATA_NUM)
		dout_en <= 'h1;
	else
		dout_en <= 'h0;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		dout <= 'h0;
	else if (cnt == DATA_NUM)
		dout <= sum;
endmodule    //multiplier_8bit

