module multiplier(
	sys_clk_i,
	sys_rst_n_i,
	din_en,
	din0,
	din1,
	dout_en,
	dout);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input din_en;
	input [15:0] din0;
	input [15:0] din1;
	output dout_en;
	output [31:0] dout;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire din_en;
	wire [15:0] din0;
	wire [15:0] din1;
	reg dout_en;
	reg [31:0] dout;
	wire [7:0] split1_A;
	wire [7:0] split2_A;
	wire [7:0] split2_B;
	wire [7:0] split1_B;

	//----Code starts here: integrated by Robei-----
	wire [15:0] dout1;
	wire [15:0] dout2;
	wire [15:0] dout3;
	wire [15:0] dout4;
	
	wire dout_en1;
	wire dout_en2;
	wire dout_en3;
	wire dout_en4;
	
	wire [31:0] sum;
	
	assign sum = (dout1<<16) + (dout2<<8) + (dout3<<8) + dout4;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		dout_en <= 'h0;
	else if (dout_en1&dout_en2&dout_en3&dout_en4)
		dout_en <= 'h1;
	else
		dout_en <= 'h0;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i)
		dout <= 'h0;
	else if (dout_en1&dout_en2&dout_en3&dout_en4)
		dout <= sum;
	//---Module instantiation---
	split split1(
		.N(din0),
		.A(split1_A),
		.B(split1_B));

	split split2(
		.N(din1),
		.A(split2_A),
		.B(split2_B));

	multiplier_8bit multiplier_8bit3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.din_en(din_en),
		.din0(split1_A),
		.din1(split2_A),
		.dout_en(dout_en1),
		.dout(dout1));

	multiplier_8bit multiplier_8bit4(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.din_en(din_en),
		.din0(split1_A),
		.din1(split2_B),
		.dout_en(dout_en2),
		.dout(dout2));

	multiplier_8bit multiplier_8bit5(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.din_en(din_en),
		.din0(split1_B),
		.din1(split2_A),
		.dout_en(dout_en3),
		.dout(dout3));

	multiplier_8bit multiplier_8bit6(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.din_en(din_en),
		.din0(split1_B),
		.din1(split2_B),
		.dout_en(dout_en4),
		.dout(dout4));

endmodule    //multiplier

