module data_split(
	data,
	d7,
	d6,
	d5,
	d4,
	d3,
	d2,
	d1,
	d0);

	//---Ports declearation: generated by Robei---
	input [31:0] data;
	output [7:0] d7;
	output [7:0] d6;
	output [7:0] d5;
	output [7:0] d4;
	output [7:0] d3;
	output [7:0] d2;
	output [7:0] d1;
	output [7:0] d0;

	wire [31:0] data;
	wire [7:0] d7;
	wire [7:0] d6;
	wire [7:0] d5;
	wire [7:0] d4;
	wire [7:0] d3;
	wire [7:0] d2;
	wire [7:0] d1;
	wire [7:0] d0;

	//----Code starts here: integrated by Robei-----
	assign d7 = (data[7]) ? 'd7 : 'd16;
	assign d6 = (data[6]) ? 'd6 : 'd16;
	assign d5 = (data[5]) ? 'd5 : 'd16;
	assign d4 = (data[4]) ? 'd4 : 'd16;
	assign d3 = (data[3]) ? 'd3 : 'd16;
	assign d2 = (data[2]) ? 'd2 : 'd16;
	assign d1 = (data[1]) ? 'd1 : 'd16;
	assign d0 = (data[0]) ? 'd0 : 'd16;
endmodule    //data_split

