module fsm_a_len(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	a_len,
	a_len_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [15:0] a_len;
	output a_len_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [15:0] a_len;
	reg a_len_ok;

	//----Code starts here: integrated by Robei-----
	reg [15:0] alen_r;
	
	localparam
		CHECK_a  = 6'b00_0001,
		CHECK_l  = 6'b00_0010,
		CHECK_e  = 6'b00_0100,
		CHECK_n  = 6'b00_1000,
		CHECK_plus = 6'b01_0000,
		CHECK_num  = 6'b10_0000;
	wire reset = ~sys_rst_n_i;
	reg [5:0] state;
	
	reg alen_en;
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		alen_en <= 1'b0;
		state <= CHECK_a;
	end
	else begin
		case (state)
			CHECK_a:
				begin
					if (data_valid && data_in == "a")
						state <= CHECK_l;
					else
						state <= CHECK_a;
				end
			CHECK_l:
				if (data_valid && data_in == "l")
	 				state <= CHECK_e;
				else if (data_valid && data_in == "a")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_a;
				else
					state <= CHECK_l;
			CHECK_e:
				if (data_valid && data_in == "e")
	 				state <= CHECK_n;
				else if (data_valid && data_in == "a")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_a;
				else
					state <= CHECK_e;
			CHECK_n:
				if (data_valid && data_in == "n")
	 				state <= CHECK_plus;
				else if (data_valid && data_in == "a")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_a;
				else
					state <= CHECK_n;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "a")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_a;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "a")
					state <= CHECK_l;
				else if (data_valid)
				begin
					if (data_in >= "0" && data_in <= "9") begin
						alen_en <= 1'b1;
						state <= CHECK_num;
					end
					else begin
						state <= CHECK_a;
					end
				end
				else begin
					alen_en <= 1'b0;
					state <= CHECK_num;
				end
			default:state <= CHECK_a;
		endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
	   alen_r <= 16'd0;
	end
	else begin
	    case (alen_en)
	       1'b1:begin
	           alen_r <= ((alen_r << 3)+(alen_r << 1)+(data_in - "0"));
	       end
	       1'b0: if (a_len_ok == 1) alen_r <= 16'd0;
	       default:;
	    endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		a_len <= 16'd22;
		a_len_ok <= 1'b0;
	end
	else if (alen_r > 16'd0 && state != CHECK_num) begin
		a_len <= alen_r;
		a_len_ok <= 1'b1;
	end
	else if (a_len_ok == 1'b1)
		a_len_ok <= 1'b0;
	else
		a_len_ok <= a_len_ok;
endmodule    //fsm_a_len

