module fsm_ppr(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	ppr,
	ppr_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [15:0] ppr;
	output ppr_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [15:0] ppr;
	reg ppr_ok;

	//----Code starts here: integrated by Robei-----
	reg [15:0] ppr_r;
		
	localparam
		CHECK_p1  = 5'b0_0001,
		CHECK_p2  = 5'b0_0010,
		CHECK_r = 5'b0_0100,
		CHECK_plus = 5'b0_1000,
		CHECK_num  = 5'b1_0000;
	wire reset = ~sys_rst_n_i;
	wire [15:0] ppr_cal;
	reg [4:0] state;
	
	reg ppr_en;
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		ppr_en <= 1'b0;
		state <= CHECK_p1;
	end
	else begin
		case (state)
			CHECK_p1:
				begin
					if (data_valid && data_in == "P")
						state <= CHECK_p2;
					else
						state <= CHECK_p1;
				end
			CHECK_p2:
				if (data_valid && data_in == "p")
	 				state <= CHECK_r;
				else if (data_valid && data_in == "P")
					state <= CHECK_p2;
				else if (data_valid)
					state <= CHECK_p1;
				else
					state <= CHECK_p2;
			CHECK_r:
				if (data_valid && data_in == "r")
					state <= CHECK_plus;
				else if (data_valid && data_in == "P")
					state <= CHECK_p2;
				else if (data_valid)
					state <= CHECK_p1;
				else
					state <= CHECK_r;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "P")
					state <= CHECK_p2;
				else if (data_valid)
					state <= CHECK_p1;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "P")
					state <= CHECK_p2;
				else if (data_valid)
				begin
					if (data_in >= "0" && data_in <= "9") begin
						ppr_en <= 1'b1;
						state <= CHECK_num;
					end
					else begin
						state <= CHECK_p1;
					end
				end
				else begin
					state <= CHECK_num;
					ppr_en <= 1'b0;
				end
			default:state <= CHECK_p1;
		endcase
	end
		
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
	   ppr_r <= 16'd0;
	end
	else begin
	    case (ppr_en)
	       1'b1:begin
	           ppr_r <= ((ppr_r << 3)+(ppr_r << 1)+(data_in - "0"));
	       end
	       1'b0: if (ppr_ok == 1) ppr_r <= 16'd0;
	       default:;
	    endcase
	end
	
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		ppr <= 16'd13;
		ppr_ok <= 1'd0;
	end
	else if ((ppr_r > 16'd0) && (state != CHECK_num)) begin
		ppr <= ppr_r;
		ppr_ok <= 1'b1;
		//ppr_r <= 16'd0;
	end
	else if (ppr_ok == 1'b1)
		ppr_ok <= 1'b0;
	else begin
		ppr_ok <= ppr_ok;
	end
endmodule    //fsm_ppr

