module fsm_b_len(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	b_len,
	b_len_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [15:0] b_len;
	output b_len_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [15:0] b_len;
	reg b_len_ok;

	//----Code starts here: integrated by Robei-----
	reg [15:0] blen_r;
	
	localparam
		CHECK_b  = 6'b00_0001,
		CHECK_l  = 6'b00_0010,
		CHECK_e  = 6'b00_0100,
		CHECK_n  = 6'b00_1000,
		CHECK_plus = 6'b01_0000,
		CHECK_num  = 6'b10_0000;
	wire reset = ~sys_rst_n_i;
	reg [5:0] state;
	
	reg blen_en;
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		blen_en <= 1'b0;
		state <= CHECK_b;
	end
	else begin
		case (state)
			CHECK_b:
				begin
					if (data_valid && data_in == "b")
						state <= CHECK_l;
					else
						state <= CHECK_b;
				end
			CHECK_l:
				if (data_valid && data_in == "l")
	 				state <= CHECK_e;
				else if (data_valid && data_in == "b")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_l;
			CHECK_e:
				if (data_valid && data_in == "e")
	 				state <= CHECK_n;
				else if (data_valid && data_in == "b")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_e;
			CHECK_n:
				if (data_valid && data_in == "n")
	 				state <= CHECK_plus;
				else if (data_valid && data_in == "b")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_n;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "b")
					state <= CHECK_l;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "b")
					state <= CHECK_l;
				else if (data_valid)
				begin
					if (data_in >= "0" && data_in <= "9") begin
						blen_en <= 1'b1;
						state <= CHECK_num;
					end
					else begin
						state <= CHECK_b;
					end
				end
				else begin
					blen_en <= 1'b0;
					state <= CHECK_num;
				end
			default:state <= CHECK_b;
		endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
	   blen_r <= 16'd0;
	end
	else begin
	    case (blen_en)
	       1'b1:begin
	           blen_r <= ((blen_r << 3)+(blen_r << 1)+(data_in - "0"));
	       end
	       1'b0: if (b_len_ok == 1) blen_r <= 16'd0;
	       default:;
	    endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		b_len <= 16'd18;
		b_len_ok <= 1'b0;
	end
	else if (blen_r > 16'd0 && state != CHECK_num) begin
		b_len <= blen_r;
		b_len_ok <= 1'b1;
	end
	else if (b_len_ok == 1'b1)
		b_len_ok <= 1'b0;
	else
		b_len_ok <= b_len_ok;
endmodule    //fsm_b_len

