module fsm_gr(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	gr,
	gr_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [15:0] gr;
	output gr_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [15:0] gr;
	reg gr_ok;

	//----Code starts here: integrated by Robei-----
	reg [15:0] gr_r;
	
	localparam
		CHECK_g  = 4'b0001,
		CHECK_r  = 4'b0010,
		CHECK_plus = 4'b0100,
		CHECK_num  = 4'b1000;
	wire reset = ~sys_rst_n_i;
	reg [3:0] state;
	
	reg gr_en;
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		gr_en <= 1'b0;
		state <= CHECK_g;
	end
	else begin
		case (state)
			CHECK_g:
				begin
					if (data_valid && data_in == "g")
						state <= CHECK_r;
					else
						state <= CHECK_g;
				end
			CHECK_r:
				if (data_valid && data_in == "r")
	 				state <= CHECK_plus;
				else if (data_valid && data_in == "g")
					state <= CHECK_r;
				else if (data_valid)
					state <= CHECK_g;
				else
					state <= CHECK_r;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "g")
					state <= CHECK_r;
				else if (data_valid)
					state <= CHECK_g;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "g")
					state <= CHECK_r;
				else if (data_valid)
				begin
					if (data_in >= "0" && data_in <= "9") begin
						gr_en <= 1'b1;
						state <= CHECK_num;
					end
					else begin
						state <= CHECK_g;
					end
				end
				else begin
					gr_en <= 1'b0;
					state <= CHECK_num;
				end
			default:state <= CHECK_g;
		endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
	   gr_r <= 16'd0;
	end
	else begin
	    case (gr_en)
	       1'b1:begin
	           gr_r <= ((gr_r << 3)+(gr_r << 1)+(data_in - "0"));
	       end
	       1'b0: if (gr_ok == 1) gr_r <= 16'd0;
	       default:;
	    endcase
	end
	
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		gr <= 16'd30;
		gr_ok <= 1'b0;
	end
	else if (gr_r > 16'd0 && state != CHECK_num) begin
		gr <= gr_r;
		gr_ok <= 1'b1;
	end
	else if (gr_ok == 1'b1)
		gr_ok <= 1'b0;
	else
		gr_ok <= gr_ok;
endmodule    //fsm_gr

