module split(
	N,
	A,
	B);

	//---Ports declearation: generated by Robei---
	input [15:0] N;
	output [7:0] A;
	output [7:0] B;

	wire [15:0] N;
	wire [7:0] A;
	wire [7:0] B;

	//----Code starts here: integrated by Robei-----
	assign A = N[15:8];
	assign B = N[7:0];
endmodule    //split

