module fsm_baud(
	sys_clk_i,
	sys_rst_n_i,
	data_in,
	data_valid,
	baud,
	baud_ok);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] data_in;
	input data_valid;
	output [2:0] baud;
	output baud_ok;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] data_in;
	wire data_valid;
	reg [2:0] baud;
	reg baud_ok;

	//----Code starts here: integrated by Robei-----
	localparam
		CHECK_b  = 6'b00_0001,
		CHECK_a  = 6'b00_0010,
		CHECK_u = 6'b00_0100,
		CHECK_d = 6'b00_1000,
		CHECK_plus = 6'b01_0000,
		CHECK_num = 6'b10_0000;
	wire reset = ~sys_rst_n_i;
	reg [5:0] state;
	    
	always@(posedge sys_clk_i or posedge reset)
	if (reset) begin
		baud_ok <= 1'b0;
		baud <= 3'd00;
		state <= CHECK_b;
	end
	else begin
		case (state)
			CHECK_b:
				begin
					baud_ok <= 1'b0;
					if (data_valid && data_in == "b")
						state <= CHECK_a;
					else
						state <= CHECK_b;
				end
			CHECK_a:
				if (data_valid && data_in == "a")
	 				state <= CHECK_u;
				else if (data_valid && data_in == "b")
					state <= CHECK_a;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_a;
			CHECK_u:
				if (data_valid && data_in == "u")
					state <= CHECK_d;
				else if (data_valid && data_in == "b")
					state <= CHECK_a;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_u;
			CHECK_d:
				if (data_valid && data_in == "d")
					state <= CHECK_plus;
				else if (data_valid && data_in == "b")
					state <= CHECK_a;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_d;
			CHECK_plus:
				if (data_valid && data_in == "+")
					state <= CHECK_num;
				else if (data_valid && data_in == "b")
					state <= CHECK_a;
				else if (data_valid)
					state <= CHECK_b;
				else
					state <= CHECK_plus;
			CHECK_num:
				if (data_valid && data_in == "b")
					state <= CHECK_a;
				else if (data_valid)
				begin
					state <= CHECK_b;
					if (data_in>="0" && data_in <= "4") begin
						baud_ok <= 1'b1;
						baud <= data_in-"0";
					end
					else
						baud_ok <= 1'b0;
					end
				else
					state <= CHECK_num;
			default:state <= CHECK_b;
		endcase
	end
endmodule    //fsm_baud

