module uart_rx(
	clk,
	reset,
	rx,
	po_data,
	po_flag);

	//----Parameters:: generated by Robei-----
	parameter baud_cnt_MAX = 'd289;

	//---Ports declearation: generated by Robei---
	input clk;
	input reset;
	input rx;
	output [7:0] po_data;
	output po_flag;

	wire clk;
	wire reset;
	wire rx;
	reg [7:0] po_data;
	reg po_flag;

	//----Code starts here: integrated by Robei-----
	//reg define
	reg rx_reg1;
	reg rx_reg2;
	reg rx_reg3;
	reg work_en;	//工作使能信号
	reg start_negedge;//下降沿检测
	reg [12:0]baud_cnt;	//比特计数器
	reg bit_flag;
	reg [3:0]bit_cnt;
	reg [7:0]rx_data;
	reg rx_flag;
	
	//三拍寄存器
	always@(posedge clk or negedge reset)
	    if(!reset)begin
	    rx_reg1 <= 1'b0;
	end
	  else begin
	    rx_reg1 <= rx;
	end
	
	always@(posedge clk or negedge reset)
	    if(!reset)begin
	    rx_reg2 <= 1'b0;
	end
	  else begin
	    rx_reg2 <= rx_reg1;
	end
	
	always@(posedge clk or negedge reset)
	    if(!reset)begin
	    rx_reg3 <= 1'b0;
	end
	  else begin
	    rx_reg3 <= rx_reg2;
	end
	
	//start_negedge
	always@(posedge clk or negedge reset)
	if(!reset)begin
	    start_negedge <= 1'b0;
	end
	else if((~rx_reg2) && (rx_reg3))
	start_negedge <= 1'b1;
	else
	start_negedge <= 1'b0;
	
	//work_en
	always@(posedge clk or negedge reset)
	if(!reset)
	  work_en <= 1'b0;
	else if(start_negedge == 1'b1)
	work_en <= 1'b1;
	else if((bit_cnt == 4'd8) && (bit_flag == 1'b1))
	work_en <= 1'b0;
	else 
	  work_en <= work_en;
	
	//baud_cnt
	always@(posedge clk or negedge reset)
	if(!reset)
	  baud_cnt<= 0;
	else if(work_en == 1'b1)begin
	    if(baud_cnt >= baud_cnt_MAX - 1'b1)
	        baud_cnt <= 0;
	    else 
	        baud_cnt <= baud_cnt + 1'b1;
	end
	else
	  baud_cnt <= 0;
	
	//bit_flag
	always@(posedge clk or negedge reset)
	if(!reset)
	  bit_flag <= 0;
	else if(work_en == 1'b1)begin
	    if(baud_cnt == baud_cnt_MAX/2)
	        bit_flag <= 1;
	    else 
	        bit_flag <= 0;
	end
	else bit_flag <= 0;
	
	//bit_cnt;
	always@(posedge clk or negedge reset)
	if(!reset)
	  bit_cnt <= 4'd0;
	 else if((bit_cnt == 4'd8) && (bit_flag == 1'b1))
	 bit_cnt <= 4'b0;
	 else if(bit_flag ==1'b1)
	 bit_cnt <= bit_cnt + 1'b1;
	
	//rx_data:输入数据进行移位
	 always@(posedge clk or negedge reset)
	 if(reset == 1'b0)
	   rx_data <= 8'b0;
	 else if((bit_cnt >= 4'd1)&&(bit_cnt <= 4'd8)&&(bit_flag == 1'b1))
	   rx_data <= {rx_reg3, rx_data[7:1]};
	
	//rx_flag
	always@(posedge clk or negedge reset)
	if(!reset)
	  rx_flag <= 1'b0;
	else if(bit_cnt == 4'd8 &&(bit_flag == 1'b1))
	  rx_flag <= 1'b1;
	else
	  rx_flag <= 1'b0;
	
	//po_data
	always@(posedge clk or negedge reset)
	if(!reset)
	  po_data <= 8'b0;
	else if(rx_flag)
	  po_data <= rx_data;
	
	//po_flag
	always@(posedge clk or negedge reset)
	if(!reset)
	  po_flag <= 1'b0;
	else if(rx_flag)
	  po_flag <= 1'b1;
	else
	  po_flag <= 1'b0;
endmodule    //uart_rx

