module uart_ble(
	clk,
	reset,
	rx_ble,
	direction_en,
	dis_en);

	//---Ports declearation: generated by Robei---
	input clk;
	input reset;
	input rx_ble;
	output direction_en;
	output dis_en;

	wire clk;
	wire reset;
	wire rx_ble;
	reg direction_en;
	reg dis_en;

	//----Code starts here: integrated by Robei-----
	wire [7:0]po_data;
	wire po_flag;
	
	reg [2:0]rx_state;
	reg useful_flag;
	reg [7:0]direction;
	reg [7:0]distance;
	reg po_flag_reg;
	parameter state_0 = 'd0,
	state_1 = 'd1,
	state_2 = 'd2,
	state_3 = 'd3,
	state_4 = 'd4,
	STATE_MAX = 'd5;
	
	//po_flag_reg
	always@(posedge clk or negedge reset)
	if(reset == 0)
		po_flag_reg <= 1'd0;
	else 
		po_flag_reg <= po_flag;
	//rx_state
	always@(posedge clk or negedge reset)
	if(reset == 0)begin
		rx_state <= state_0;
		useful_flag <= 1'd0;
	  direction <= 'd0;
	  distance <= 'd0;
	end
	else 
		case(rx_state)
		  state_0:begin
					if((po_flag == 'd1)&&(po_data == "@"))
						rx_state <= state_1;
					else
						rx_state <= state_0;
			 end
			state_1:begin
					useful_flag <= 1'd0;
					if((po_flag == 'd1)&&(po_data == "@"))
						rx_state <= state_2;
					else
						rx_state <= rx_state;				
			end
			state_2:begin
					if(po_flag == 'd1)begin
						rx_state <= state_3;
						distance <= po_data;
					end
					else
						rx_state <= rx_state;				
			end
			state_3:begin
					if(po_flag == 'd1)begin
						rx_state <= state_4;
						direction <= po_data;
					end
					else
						rx_state <= rx_state;				
			end
			state_4:begin
					if((po_flag == 'd1)&&(po_data == "#"))begin
						rx_state <= state_0;
						useful_flag <= 1'd1;
					end
					else if((po_flag == 'd1)&&(po_data != "#"))begin
						rx_state <= state_0;				
						useful_flag <= 1'd0;
					end
					else begin
						rx_state <= rx_state;
						useful_flag <= 1'd0;
					end
			end
			default:begin
					rx_state <= state_0;
			end
		endcase
	
	//direction_en
	always@(posedge clk or negedge reset)
	if(reset == 0)
		direction_en <= 1'd0;
	else if((useful_flag == 1'b1)&&(direction == "L"))
	  direction_en <= 1'd0;
	else if((useful_flag == 1'b1)&&(direction == "R"))
	  direction_en <= 1'd1;
	else 
	  direction_en <= direction_en;
	//distance_en
	always@(posedge clk or negedge reset)
	if(reset == 0)
		dis_en <= 1'd0;
	else if((useful_flag == 1'b1)&&(distance == "T"))
		dis_en <= 1'd1;
	else if((useful_flag == 1'b1)&&(distance == "F"))
		dis_en <= 1'd0;
	else
		dis_en <= dis_en;
	
	
	//---Module instantiation---
	uart_rx #( 'd3472) uart_rx1(
		.clk(clk),
		.reset(reset),
		.rx(rx_ble),
		.po_data(po_data),
		.po_flag(po_flag));

endmodule    //uart_ble

