module uart_data_tx(
	sys_clk_i,
	sys_rst_n_i,
	baud_set,
	send_en,
	data,
	uart_tx,
	uart_state,
	tx_done);

	//----Parameters:: generated by Robei-----
	parameter DATA_WIDTH = 152;
	parameter MSB_FIRST = 1;

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [2:0] baud_set;
	input send_en;
	input [DATA_WIDTH-1:0] data;
	output uart_tx;
	output uart_state;
	output tx_done;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [2:0] baud_set;
	wire send_en;
	wire [DATA_WIDTH-1:0] data;
	wire uart_tx;
	wire uart_state;
	reg tx_done;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_byte;
	reg byte_send_en;
	wire byte_tx_done;
	
	reg [8:0] cnt;
	reg [1:0] state;
	reg [DATA_WIDTH - 1 : 0]data_r;
	    
	localparam S0 = 0;  //等待发送请求
	localparam S1 = 1;  //发起单字节数据发送
	localparam S2 = 2;  //等待单字节数据发送完成
	localparam S3 = 3;  //检查所以数据是否发送完成
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		data_byte <= 0;
		byte_send_en <= 0;
		state <= S0;
		cnt <= 0;
	end
	else begin
		case (state)
			S0:
				begin
					data_byte <= 0;
					cnt <= 0;
					tx_done <= 0;
					if (send_en) begin
						state <= S1;
						data_r <= data;
					end
					else begin
						state <= S0;
						data_r <= data_r;
					end
				end
			S1:
				begin
					byte_send_en = 1;
					if (MSB_FIRST == 1) begin
						data_byte <= data_r[DATA_WIDTH-1:DATA_WIDTH-8];
						data_r <= data_r << 8;
					end
					else begin
						data_byte <= data_r[7:0];
						data_r <= data_r >> 8;
					end
					state <= S2;
				end
			S2:
				begin
					byte_send_en <= 0;
					if (byte_tx_done) begin
						state <= S3; 
						cnt <= cnt + 9'd8;
					end
					else
						state <= S2;
					end
			S3:
				begin
					if (cnt >= DATA_WIDTH) begin
						state <= S0;
						cnt <= 0;
						tx_done <= 1;
					end
					else begin
						state <= S1;
						tx_done <= 0;
					end
				end
			default:state <= S0;
		endcase
	end
	//---Module instantiation---
	uart_byte_tx uart_byte_tx1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_byte(data_byte),
		.send_en(byte_send_en),
		.baud_set(baud_set),
		.uart_tx(uart_tx),
		.tx_done(byte_tx_done),
		.uart_state(uart_state));

endmodule    //uart_data_tx

