module uart_ble_adjust(
	sys_clk_i,
	sys_rst_n_i,
	rx_data,
	rx_done,
	adjust,
	theta_ad);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] rx_data;
	input rx_done;
	output [7:0] adjust;
	output [7:0] theta_ad;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] rx_data;
	wire rx_done;
	reg [7:0] adjust;
	reg [7:0] theta_ad;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_str [5:0];
	
	always@(posedge sys_clk_i)
	if (rx_done) begin
		data_str[5] <= #1 rx_data;
		data_str[4] <= #1 data_str[5];
		data_str[3] <= #1 data_str[4];
		data_str[2] <= #1 data_str[3];
		data_str[1] <= #1 data_str[2];
		data_str[0] <= #1 data_str[1];
	end
	    
	reg r_rx_done;
	always@(posedge sys_clk_i)
		r_rx_done <= rx_done;
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		adjust <= 8'd0; 
		theta_ad <= 8'd0;
	end
	else if (r_rx_done) begin
		if ((data_str[0] == 8'hAC) && (data_str[1] == 8'hBD) && (data_str[5] == 8'hEF)) begin
			if ((data_str[2] >= 8'd1) && (data_str[2] <= 8'd4))
			begin
				case (data_str[2])
				1:	
					begin
						adjust[0] <= (data_str[3] == 'h01) ? 1'b1 : 1'b0;
						adjust[1] <= (data_str[3] == 'h10) ? 1'b1 : 1'b0;
					end
				2:
					begin
						adjust[2] <= (data_str[3] == 'h01) ? 1'b1 : 1'b0;
						adjust[3] <= (data_str[3] == 'h10) ? 1'b1 : 1'b0;
					end
				3:
					begin
						adjust[4] <= (data_str[3] == 'h01) ? 1'b1 : 1'b0;
						adjust[5] <= (data_str[3] == 'h10) ? 1'b1 : 1'b0;
					end
				4:
					begin
						adjust[6] <= (data_str[3] == 'h01) ? 1'b1 : 1'b0;
						adjust[7] <= (data_str[3] == 'h10) ? 1'b1 : 1'b0;
					end
				default:
					begin
						adjust[0] <= adjust[0];
						adjust[1] <= adjust[1];
						adjust[2] <= adjust[2];
						adjust[3] <= adjust[3];
						adjust[4] <= adjust[4];
						adjust[5] <= adjust[5];
						adjust[6] <= adjust[6];
						adjust[7] <= adjust[7];
					end
				endcase
				theta_ad <= data_str[4];
			end
		end
		else begin
			adjust <= 12'd0;
			theta_ad <= theta_ad;
		end
	end
	else begin
		adjust <= 12'd0;
		theta_ad <= theta_ad;
	end
	
	
endmodule    //uart_ble_adjust

