module uart_cmd(
	sys_clk_i,
	sys_rst_n_i,
	rx_data,
	rx_done,
	x_speed,
	y_speed,
	z_speed,
	stop);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] rx_data;
	input rx_done;
	output [15:0] x_speed;
	output [15:0] y_speed;
	output [15:0] z_speed;
	input stop;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] rx_data;
	wire rx_done;
	reg [15:0] x_speed;
	reg [15:0] y_speed;
	reg [15:0] z_speed;
	wire stop;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_str [8:0];
	
	always@(posedge sys_clk_i)
	if (rx_done) begin
		data_str[8] <= #1 rx_data;
		data_str[7] <= #1 data_str[8];
		data_str[6] <= #1 data_str[7];
		data_str[5] <= #1 data_str[6];
		data_str[4] <= #1 data_str[5];
		data_str[3] <= #1 data_str[4];
		data_str[2] <= #1 data_str[3];
		data_str[1] <= #1 data_str[2];
		data_str[0] <= #1 data_str[1];
	end
	    
	reg r_rx_done;
	always@(posedge sys_clk_i)
		r_rx_done <= rx_done;
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		x_speed <= #1 16'd0;
		y_speed <= #1 16'd0;
		z_speed <= #1 16'd0;
	end
	else if (stop&&(~r_rx_done)) begin
		x_speed <= 16'd0;
		y_speed <= 16'd0;
		z_speed <= 16'd0;
	end
	else if (r_rx_done&&(~stop)) begin
		if ((data_str[0] == 8'h55) && (data_str[1] == 8'hA5) && (data_str[8] == 8'hF0)) begin
			if (data_str[2] == 8'h00)
				x_speed <= data_str[3];
			else if (data_str[2] == 8'h01)
				x_speed <= -data_str[3];
			if (data_str[4] == 8'h00)
				y_speed <= data_str[5];
			else if (data_str[4] == 8'h01)
				y_speed <= -data_str[5];
			if (data_str[6] == 8'h00)
				z_speed <= data_str[7];
			else if (data_str[6] == 8'h01)
				z_speed <= -data_str[7];
		end
		else begin
			x_speed <= x_speed;
			y_speed <= y_speed;
			z_speed <= z_speed;
		end
	end
	else begin
		x_speed <= x_speed;
		y_speed <= y_speed;
		z_speed <= z_speed;
	end
endmodule    //uart_cmd

