module uart_ctrl(
	sys_clk_i,
	sys_rst_n_i,
	uart_rx,
	uart_tx,
	x_speed,
	y_speed,
	z_speed,
	pulse_data,
	wheel,
	a_length,
	b_length,
	key_in,
	distance_en,
	direction_en,
	baud_set);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input uart_rx;
	output uart_tx;
	output [15:0] x_speed;
	output [15:0] y_speed;
	output [15:0] z_speed;
	output [31:0] pulse_data;
	output [1:0] wheel;
	output [15:0] a_length;
	output [15:0] b_length;
	input key_in;
	input distance_en;
	input direction_en;
	output [2:0] baud_set;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire uart_rx;
	wire uart_tx;
	wire [15:0] x_speed;
	wire [15:0] y_speed;
	wire [15:0] z_speed;
	reg [31:0] pulse_data;
	wire [1:0] wheel;
	wire [15:0] a_length;
	wire [15:0] b_length;
	wire key_in;
	wire distance_en;
	wire direction_en;
	wire [2:0] baud_set;
	wire [7:0] uart_byte_rx1_data_byte;
	wire uart_byte_rx1_rx_done;
	wire [15:0] fsm_gr9_gr;
	wire [15:0] fsm_ppr10_ppr;
	wire [2:0] fsm_baud2_baud;
	assign baud_set = fsm_baud2_baud;

	//----Code starts here: integrated by Robei-----
	//wire [2:0] baud_set;
	reg send_en;
	wire [151:0] send_str;
	wire tx_done;
	
	wire baud_ok;
	wire gr_ok;
	wire ppr_ok;
	wire wheel_ok;
	wire a_len_ok;
	wire b_len_ok;
	
	wire mul_ok;
	wire div_ok;
	wire error;
	
	reg mul_en;
	reg div_en;
	
	wire [31:0] mul_num;
	reg [31:0] dividend_r;
	wire [31:0] pulse_data_w;
	
	reg [2:0] state;
	
	assign send_str =  "Set Successful!\r\n" ;
	
	wire stop;
	wire key_flag;
	wire key_state;
	assign stop = key_flag && (~key_state);
	
	localparam
		IDLE = 0,
		MUL = 1,
		WAIT_MUL = 2,
		DIV = 3,
		WAIT_DIV = 4,
		SEND = 5,
		FINISH = 6;
	
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		send_en <= 1'b0;
		mul_en <= 1'b0;
		div_en <= 1'b0;
		dividend_r <= 32'd12000;
		pulse_data <= 32'd30;
		state <= IDLE;
	end
	else begin
		case (state)
			IDLE: begin
				send_en <= 1'b0;
				mul_en <= 1'b0;
				div_en <= 1'b0;
				if (baud_ok || wheel_ok || a_len_ok || b_len_ok)
					state <= SEND;
				else if (ppr_ok || gr_ok) begin
					state <= MUL;
				end
				else
					state <= IDLE;
			end
			MUL:begin
				mul_en <= 1'b1;
				state <= WAIT_MUL;
			end
			WAIT_MUL:begin
				mul_en <= 1'b0;
				if (mul_ok)
					state <= DIV;
				else
					state <= WAIT_MUL;
			end
			DIV:begin
				div_en <= 1'b1;
				if (mul_num<=32'd1200)
					dividend_r <= 32'd12000;
				else
					dividend_r <= 32'd120000;
				state <= WAIT_DIV;
			end
			WAIT_DIV:begin
				div_en <= 1'b0;
				if (div_ok) begin
					state <= SEND;
					pulse_data <= pulse_data_w;
				end
				else
					state <= WAIT_DIV;
			end
			SEND:begin
				send_en <= 1'b1;
				state <= FINISH;
			end
			FINISH:begin
				send_en <= 1'b0;
				if (tx_done)
					state <= IDLE;
				else
					state <= FINISH;
					//state <= IDLE; //for test
			end
			default:state <= IDLE;
		endcase
	end
	
	wire [15:0] x_speed_c;
	wire [15:0] y_speed_c;
	wire [15:0] z_speed_c;
	
	wire [15:0] x_speed_d;
	wire [15:0] y_speed_d;
	wire [15:0] z_speed_d;
	
	wire dance_ack;
	
	assign x_speed = (dance_ack == 1'b1) ? x_speed_d :
										(distance_en == 1'b0) ? x_speed_c : 16'd0;
	assign y_speed = (dance_ack == 1'b1) ? y_speed_d :
										(distance_en == 1'b0) ? y_speed_c :
										(direction_en == 1'b0) ? -16'd10 : 16'd10;
	assign z_speed = (dance_ack == 1'b1) ? z_speed_d : z_speed_c;
	//---Module instantiation---
	uart_byte_rx uart_byte_rx1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.uart_rx(uart_rx),
		.baud_set(fsm_baud2_baud),
		.data_byte(uart_byte_rx1_data_byte),
		.rx_done(uart_byte_rx1_rx_done));

	fsm_baud fsm_baud2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.baud(fsm_baud2_baud),
		.baud_ok(baud_ok));

	fsm_wheel fsm_wheel5(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.wheel(wheel),
		.wheel_ok(wheel_ok));

	uart_cmd uart_cmd6(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.rx_data(uart_byte_rx1_data_byte),
		.rx_done(uart_byte_rx1_rx_done),
		.x_speed(x_speed_c),
		.y_speed(y_speed_c),
		.z_speed(z_speed_c),
		.stop(stop));

	multiplier multiplier7(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.din_en(mul_en),
		.din0(fsm_gr9_gr),
		.din1(fsm_ppr10_ppr),
		.dout_en(mul_ok),
		.dout(mul_num));

	divider #(32,32) divider8(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.start(div_en),
		.dividend(dividend_r),
		.divisor(mul_num),
		.ready( ),
		.error(error),
		.quotient_vld(div_ok),
		.remainder( ),
		.quotient(pulse_data_w));

	uart_data_tx #( 152, 1) uart_data_tx9(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.baud_set(baud_set),
		.send_en(send_en),
		.data(send_str),
		.uart_tx(uart_tx),
		.uart_state( ),
		.tx_done(tx_done));

	fsm_gr fsm_gr9(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.gr(fsm_gr9_gr),
		.gr_ok(gr_ok));

	fsm_ppr fsm_ppr10(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.ppr(fsm_ppr10_ppr),
		.ppr_ok(ppr_ok));

	fsm_a_len fsm_a_len11(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.a_len(a_length),
		.a_len_ok(a_len_ok));

	fsm_b_len fsm_b_len12(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.data_in(uart_byte_rx1_data_byte),
		.data_valid(uart_byte_rx1_rx_done),
		.b_len(b_length),
		.b_len_ok(b_len_ok));

	key_filter key_filter12(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.key_in(key_in),
		.key_flag(key_flag),
		.key_state(key_state));

	dance_cmd dance_cmd13(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.rx_data(uart_byte_rx1_data_byte),
		.rx_done(uart_byte_rx1_rx_done),
		.x_speed(x_speed_d),
		.y_speed(y_speed_d),
		.z_speed(z_speed_d),
		.dance_ack(dance_ack));

endmodule    //uart_ctrl

