module uart_arm_ble(
	sys_clk_i,
	sys_rst_n_i,
	rx_data,
	rx_done,
	color_sel,
	observe_en,
	motion_en,
	pack_en,
	catch_en,
	put_en);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] rx_data;
	input rx_done;
	output [7:0] color_sel;
	output [1:0] observe_en;
	output motion_en;
	output pack_en;
	output catch_en;
	output [1:0] put_en;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] rx_data;
	wire rx_done;
	reg [7:0] color_sel;
	reg [1:0] observe_en;
	reg motion_en;
	reg pack_en;
	reg catch_en;
	reg [1:0] put_en;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_str [8:0];
	
	always@(posedge sys_clk_i)
	if (rx_done) begin
		data_str[8] <= #1 rx_data;
		data_str[7] <= #1 data_str[8];
		data_str[6] <= #1 data_str[7];
		data_str[5] <= #1 data_str[6];
		data_str[4] <= #1 data_str[5];
		data_str[3] <= #1 data_str[4];
		data_str[2] <= #1 data_str[3];
		data_str[1] <= #1 data_str[2];
		data_str[0] <= #1 data_str[1];
	end
	    
	reg r_rx_done;
	always@(posedge sys_clk_i)
		r_rx_done <= rx_done;
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		color_sel <= 8'd0;  //Ä¬ÈÏRED
		observe_en <= 1'd0;
		motion_en <= 1'd0;
		pack_en <= 1'b0;
		put_en <= 2'b0;
		catch_en <= 1'b0;
	end
	else if (r_rx_done) begin
		if ((data_str[0] == 8'hDD) && (data_str[1] == 8'hEE) && (data_str[8] == 8'hFF)) begin
			color_sel <= (data_str[2]);
			observe_en[0] <= (data_str[3][0]);
			observe_en[1] <= (data_str[3][4]);
			motion_en <= (data_str[4] & 1'b1);
			pack_en <= (data_str[5] & 1'b1);
			put_en[0] <= (data_str[6][0]);
			put_en[1] <= (data_str[6][4]);
			catch_en <= (data_str[7] & 1'b1);
		end
		else begin
			color_sel <= color_sel;  //Ä¬ÈÏRED
			observe_en <= observe_en;
			motion_en <= motion_en;
			pack_en <= pack_en;
			put_en <= put_en;
			catch_en <= catch_en;
		end
	end
	else begin
		color_sel <= color_sel;  //Ä¬ÈÏRED
		observe_en <= observe_en;
		motion_en <= motion_en;
		pack_en <= pack_en;
		put_en <= put_en;
		catch_en <= catch_en;
	end
	
	
	
	
endmodule    //uart_arm_ble

