module uart_arm_mv(
	sys_clk_i,
	sys_rst_n_i,
	rx_data,
	rx_done,
	color_sel,
	X,
	Y,
	theta);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input [7:0] rx_data;
	input rx_done;
	input [7:0] color_sel;
	output [15:0] X;
	output [15:0] Y;
	output [31:0] theta;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire [7:0] rx_data;
	wire rx_done;
	wire [7:0] color_sel;
	reg [15:0] X;
	reg [15:0] Y;
	reg [31:0] theta;

	//----Code starts here: integrated by Robei-----
	reg [7:0] data_str [8:0];
	reg [15:0] x_i;
	reg [15:0] y_i;
	reg [31:0] theta_i;
	
	always@(posedge sys_clk_i)
	if (rx_done) begin
		data_str[8] <= #1 rx_data;
		data_str[7] <= #1 data_str[8];
		data_str[6] <= #1 data_str[7];
		data_str[5] <= #1 data_str[6];
		data_str[4] <= #1 data_str[5];
		data_str[3] <= #1 data_str[4];
		data_str[2] <= #1 data_str[3];
		data_str[1] <= #1 data_str[2];
		data_str[0] <= #1 data_str[1];
	end
	    
	reg r_rx_done;
	always@(posedge sys_clk_i)
		r_rx_done <= rx_done;
	    
	always@(posedge sys_clk_i or negedge sys_rst_n_i)
	if (!sys_rst_n_i) begin
		X <= 16'd0;
		Y <= 16'd0;
		theta <= 32'd0;
		x_i <= 16'd0;
		y_i <= 16'd0;
		theta_i <= 32'd0;
	end
	else if (r_rx_done) begin
		if ((data_str[0] == 8'hAA) && (data_str[1] == 8'hBB) && (data_str[8] == 8'hCC)) begin
			if (color_sel == data_str[2])
			begin
				if (data_str[3] == 8'h00)
					x_i <= data_str[4];
				else if (data_str[3] == 8'h01)
					x_i <= -data_str[4];
				if (data_str[5] == 8'h00)
					y_i <= data_str[6];
				else if (data_str[5] == 8'h01)
					y_i <= -data_str[6];
				theta_i <= data_str[7];
			end
		end
		else begin
			x_i <= x_i;
			y_i <= y_i;
			theta_i <= theta_i;
		end
	end
	else begin
		X <= (x_i <<<  8);
		Y <= (y_i <<< 8);
		theta <= (theta_i <<< 16);
		x_i <= x_i;
		y_i <= y_i;
		theta_i <= theta_i;
	end
	
endmodule    //uart_arm_mv

