module arm_top(
	sys_clk_i,
	sys_rst_n_i,
	mv_rx,
	ble_rx,
	steera,
	steerb,
	steerc,
	steerd,
	steere,
	steerf);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input mv_rx;
	input ble_rx;
	output steera;
	output steerb;
	output steerc;
	output steerd;
	output steere;
	output steerf;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire mv_rx;
	wire ble_rx;
	wire steera;
	wire steerb;
	wire steerc;
	wire steerd;
	wire steere;
	wire steerf;
	wire [7:0] uart_byte_rx1_data_byte;
	wire uart_byte_rx1_rx_done;
	wire [7:0] uart_arm_ble11_color_sel;
	wire [7:0] uart_byte_rx2_data_byte;
	wire uart_byte_rx2_rx_done;
	wire clk_div12_clk_o;
	wire [15:0] uart_arm_mv10_X;
	wire [15:0] uart_arm_mv10_Y;
	wire [31:0] uart_arm_mv10_theta;
	wire [1:0] uart_arm_ble11_observe_en;
	wire uart_arm_ble11_motion_en;
	wire uart_arm_ble11_pack_en;
	wire uart_arm_ble11_catch_en;
	wire [31:0] motion3_pulsea;
	wire [31:0] motion3_pulseb;
	wire [31:0] motion3_pulsec;
	wire [31:0] motion3_pulsed;
	wire [31:0] motion3_pulsee;
	wire [31:0] motion3_pulsef;
	wire [7:0] uart_ble_adjust13_adjust;
	wire [7:0] uart_ble_adjust13_theta_ad;
	wire [1:0] uart_arm_ble11_put_en;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	uart_byte_rx uart_byte_rx1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.uart_rx(mv_rx),
		.baud_set(3'd0),
		.data_byte(uart_byte_rx1_data_byte),
		.rx_done(uart_byte_rx1_rx_done));

	uart_byte_rx uart_byte_rx2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.uart_rx(ble_rx),
		.baud_set(3'd0),
		.data_byte(uart_byte_rx2_data_byte),
		.rx_done(uart_byte_rx2_rx_done));

	motion motion3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.clk(clk_div12_clk_o),
		.X(uart_arm_mv10_X),
		.Y(uart_arm_mv10_Y),
		.theta(uart_arm_mv10_theta),
		.pulsea(motion3_pulsea),
		.pulseb(motion3_pulseb),
		.pulsec(motion3_pulsec),
		.pulsed(motion3_pulsed),
		.pulsee(motion3_pulsee),
		.pulsef(motion3_pulsef),
		.observe_en(uart_arm_ble11_observe_en),
		.motion_en(uart_arm_ble11_motion_en),
		.pack_en(uart_arm_ble11_pack_en),
		.catch_en(uart_arm_ble11_catch_en),
		.adjust(uart_ble_adjust13_adjust),
		.theta_ad(uart_ble_adjust13_theta_ad),
		.put_en(uart_arm_ble11_put_en));

	steer_pwm steer_pwm4(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulsea),
		.pwm_gen_en(1'b1),
		.pwm_out(steera));

	steer_pwm steer_pwm5(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulseb),
		.pwm_gen_en(1'b1),
		.pwm_out(steerb));

	steer_pwm steer_pwm6(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulsec),
		.pwm_gen_en(1'b1),
		.pwm_out(steerc));

	steer_pwm steer_pwm7(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulsed),
		.pwm_gen_en(1'b1),
		.pwm_out(steerd));

	steer_pwm steer_pwm8(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulsee),
		.pwm_gen_en(1'b1),
		.pwm_out(steere));

	steer_pwm steer_pwm9(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.theta(motion3_pulsef),
		.pwm_gen_en(1'b1),
		.pwm_out(steerf));

	uart_arm_mv uart_arm_mv10(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.rx_data(uart_byte_rx1_data_byte),
		.rx_done(uart_byte_rx1_rx_done),
		.color_sel(uart_arm_ble11_color_sel),
		.X(uart_arm_mv10_X),
		.Y(uart_arm_mv10_Y),
		.theta(uart_arm_mv10_theta));

	uart_arm_ble uart_arm_ble11(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.rx_data(uart_byte_rx2_data_byte),
		.rx_done(uart_byte_rx2_rx_done),
		.color_sel(uart_arm_ble11_color_sel),
		.observe_en(uart_arm_ble11_observe_en),
		.motion_en(uart_arm_ble11_motion_en),
		.pack_en(uart_arm_ble11_pack_en),
		.catch_en(uart_arm_ble11_catch_en),
		.put_en(uart_arm_ble11_put_en));

	clk_div #(  3333333) clk_div12(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.clk_en(1'b1),
		.clk_o(clk_div12_clk_o));

	uart_ble_adjust uart_ble_adjust13(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.rx_data(uart_byte_rx2_data_byte),
		.rx_done(uart_byte_rx2_rx_done),
		.adjust(uart_ble_adjust13_adjust),
		.theta_ad(uart_ble_adjust13_theta_ad));

endmodule    //arm_top

