module dc_motor_driver_top(
	sys_clk_i,
	sys_rst_n_i,
	motor_spin_dir,
	motor_rpm_set,
	motor_encoder_A_i,
	motor_encoder_B_i,
	pulse_data,
	motor_ain1_o,
	motor_ain2_o,
	motor_pwm_o);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input motor_spin_dir;
	input [15:0] motor_rpm_set;
	input motor_encoder_A_i;
	input motor_encoder_B_i;
	input [31:0] pulse_data;
	output motor_ain1_o;
	output motor_ain2_o;
	output motor_pwm_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire motor_spin_dir;
	wire [15:0] motor_rpm_set;
	wire motor_encoder_A_i;
	wire motor_encoder_B_i;
	wire [31:0] pulse_data;
	wire motor_ain1_o;
	wire motor_ain2_o;
	wire motor_pwm_o;

	//----Code starts here: integrated by Robei-----
	wire controller_spin_dir;
	wire[15:0]  motor_acc_set;
	
	//controller_spin_dir == 1 反转   controller_spin_dir == 0 正转
	assign motor_ain1_o    = ( controller_spin_dir == 1'b1 ) ? 1'b0 : 1'b1;
	assign motor_ain2_o    = ( controller_spin_dir == 1'b1 ) ? 1'b1 : 1'b0;
	
	wire[15:0] Speed_PID_parameter_P;
	wire[15:0] Speed_PID_parameter_I;
	wire[15:0] Speed_PID_parameter_D;
	
	assign Speed_PID_parameter_P = 16'd20;
	assign Speed_PID_parameter_I = 16'd1;
	assign Speed_PID_parameter_D = 16'd0;
	//---Module instantiation---
	dc_motor_driver dc_motor_driver1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.motor_spin_dir_i(motor_spin_dir),
		.motor_rpm_set_i(motor_rpm_set),
		.motor_acc_set_i(motor_acc_set),
		.Speed_PID_parameter_P(Speed_PID_parameter_P),
		.Speed_PID_parameter_I(Speed_PID_parameter_I),
		.Speed_PID_parameter_D(Speed_PID_parameter_D),
		.motor_encoder_A_i(motor_encoder_A_i),
		.motor_encoder_B_i(motor_encoder_B_i),
		.motor_spin_dir_o( ),
		.controller_spin_dir_o(controller_spin_dir),
		.motor_pwm_driver_o(motor_pwm_o),
		.pulse_data(pulse_data));

endmodule    //dc_motor_driver_top

