module disp_top(
	clk,
	reset,
	rx,
	shcp,
	stcp,
	ds,
	key_in,
	dht11,
	rx_left,
	rx_right,
	distance_en,
	direction_en,
	rx_ble);

	//---Ports declearation: generated by Robei---
	input clk;
	input reset;
	input rx;
	output shcp;
	output stcp;
	output ds;
	input key_in;
	inout dht11;
	input rx_left;
	input rx_right;
	output distance_en;
	output direction_en;
	input rx_ble;

	wire clk;
	wire reset;
	wire rx;
	wire shcp;
	wire stcp;
	wire ds;
	wire key_in;
	wire dht11;
	wire rx_left;
	wire rx_right;
	reg distance_en;
	wire direction_en;
	wire rx_ble;

	//----Code starts here: integrated by Robei-----
	//parameter define
	parameter dist_avoid_MM = 'd470;
	//wire define
	wire[15:0]dist;
	wire[15:0]dist_left;
	wire[15:0]dist_right;
	wire[31:0]disp_data;
	wire [15:0]dist_reg;
	wire [15:0]dist_reg_left;
	wire [15:0]dist_reg_right;
	wire key_flag;
	wire [15:0]dht11_data;
	//reg define
	reg [31:0]disp_data_reg;
	reg [2:0]state_cnt;
	parameter STATE_CNT_MAX = 'd4;
	parameter disp0_state = 'd0,     //显示编号
	disp1_state = 'd1,                       //显示温湿度信息
	disp2_state = 'd2,                      //显示前面测距信息
	disp3_state = 'd3,                      //显示左边测距信息
	disp4_state = 'd4;                      //显示右边测距信息
	always@(posedge clk or negedge reset)
	if(reset == 0)
		state_cnt <= 'd0;
	else if(state_cnt == STATE_CNT_MAX+1)
		state_cnt <= 'd0;
	else if(key_flag == 1)
		state_cnt <= state_cnt + 1'd1;
	else
		state_cnt <= state_cnt;
	//disp_data_reg
	always@(posedge clk or negedge reset)
	if(reset == 0)
		disp_data_reg <= 32'hFFFF_FFFF;
	else begin
		case(state_cnt)
			'd0:disp_data_reg <= 32'hC1CC_1019;  //显示队伍编号
			'd1:disp_data_reg <= {8'hFF,dht11_data[15:8],8'hFF,dht11_data[7:0]};   //显示温湿度信息
			'd2:disp_data_reg <= {16'hd0ff,dist};
			'd3:disp_data_reg <= {16'hd1ff,dist_left};
			'd4:disp_data_reg <= {16'hd2ff,dist_right};	
			default:disp_data_reg <= 32'hC1CC_1019;
		endcase
	end
	
	//disp_data
	assign disp_data = disp_data_reg;
	
	wire dis_en;
	//avoid_en
	always@(posedge clk or negedge reset)
	if(reset ==0)
		distance_en <= 'd0;
	else if(dis_en == 'd1)begin
		if((dist_reg < dist_avoid_MM)||(dist_reg_left < dist_avoid_MM)||(dist_reg_right<dist_avoid_MM))
			distance_en <= 'd1;
	  else if((dist_reg > dist_avoid_MM)&&(dist_reg_left > dist_avoid_MM)&&(dist_reg_right>dist_avoid_MM))
	     distance_en <= 'd0;
	  else
	     distance_en <= distance_en;
	end
	else 
		distance_en <= 'd0;
	//---Module instantiation---
	hex_top hex_top2(
		.clk(clk),
		.reset_n(reset),
		.sh_cp(shcp),
		.st_cp(stcp),
		.ds(ds),
		.disp_data(disp_data));

	dht11_ctrl dht11_ctrl4(
		.sys_clk(clk),
		.sys_rst_n(reset),
		.data_out(dht11_data),
		.dht11(dht11));

	distance distance6(
		.clk(clk),
		.reset(reset),
		.uart_rx(rx),
		.dist(dist),
		.dist_reg(dist_reg));

	distance distance5(
		.clk(clk),
		.reset(reset),
		.uart_rx(rx_left),
		.dist(dist_left),
		.dist_reg(dist_reg_left));

	distance distance7(
		.clk(clk),
		.reset(reset),
		.uart_rx(rx_right),
		.dist(dist_right),
		.dist_reg(dist_reg_right));

	switch_key_filter switch_key_filter6(
		.clk(clk),
		.reset(reset),
		.key_in(key_in),
		.key_flag(key_flag));

	uart_ble uart_ble7(
		.clk(clk),
		.reset(reset),
		.rx_ble(rx_ble),
		.direction_en(direction_en),
		.dis_en(dis_en));

endmodule    //disp_top

