module hex_top(
	clk,
	reset_n,
	sh_cp,
	st_cp,
	ds,
	disp_data);

	//---Ports declearation: generated by Robei---
	input clk;
	input reset_n;
	output sh_cp;
	output st_cp;
	output ds;
	input [31:0] disp_data;

	wire clk;
	wire reset_n;
	wire sh_cp;
	wire st_cp;
	wire ds;
	wire [31:0] disp_data;

	//----Code starts here: integrated by Robei-----
	wire [7:0] sel;//数码管位选（选择当前要显示的数码管）
	wire [6:0] seg;//数码管段选（当前要显示的内容)
	
	wire en;
	wire s_en;
	wire [15:0] hc595_data;
	
	assign en = 1;
	assign s_en = 1;
	assign hc595_data = {1'd1,seg,sel};
	//assign disp_data_num =  32'hC1CC_1019;
	//---Module instantiation---
	hc595_driver hc595_driver2(
		.clk(clk),
		.reset_n(reset_n),
		.data(hc595_data),
		.s_en(s_en),
		.sh_cp(sh_cp),
		.st_cp(st_cp),
		.ds(ds));

	hex8 hex82(
		.clk(clk),
		.reset_n(reset_n),
		.en(en),
		.disp_data(disp_data),
		.sel(sel),
		.seg(seg));

endmodule    //hex_top

