module motor_chip_top(
	sys_clk_i,
	sys_rst_n_i,
	uart_rx,
	motor_encoder_A_1,
	motor_encoder_B_1,
	motor_encoder_A_2,
	motor_encoder_B_2,
	motor_encoder_A_3,
	motor_encoder_B_3,
	motor_encoder_A_4,
	motor_encoder_B_4,
	M1_in1,
	M1_in2,
	M1_pwm,
	M2_in1,
	M2_in2,
	M2_pwm,
	M3_in1,
	M3_in2,
	M3_pwm,
	M4_in1,
	M4_in2,
	M4_pwm,
	uart_tx,
	stop,
	distance_en,
	direction_en,
	baud_set);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input uart_rx;
	input motor_encoder_A_1;
	input motor_encoder_B_1;
	input motor_encoder_A_2;
	input motor_encoder_B_2;
	input motor_encoder_A_3;
	input motor_encoder_B_3;
	input motor_encoder_A_4;
	input motor_encoder_B_4;
	output M1_in1;
	output M1_in2;
	output M1_pwm;
	output M2_in1;
	output M2_in2;
	output M2_pwm;
	output M3_in1;
	output M3_in2;
	output M3_pwm;
	output M4_in1;
	output M4_in2;
	output M4_pwm;
	output uart_tx;
	input stop;
	input distance_en;
	input direction_en;
	output [2:0] baud_set;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire uart_rx;
	wire motor_encoder_A_1;
	wire motor_encoder_B_1;
	wire motor_encoder_A_2;
	wire motor_encoder_B_2;
	wire motor_encoder_A_3;
	wire motor_encoder_B_3;
	wire motor_encoder_A_4;
	wire motor_encoder_B_4;
	wire M1_in1;
	wire M1_in2;
	wire M1_pwm;
	wire M2_in1;
	wire M2_in2;
	wire M2_pwm;
	wire M3_in1;
	wire M3_in2;
	wire M3_pwm;
	wire M4_in1;
	wire M4_in2;
	wire M4_pwm;
	wire uart_tx;
	wire stop;
	wire distance_en;
	wire direction_en;
	wire [2:0] baud_set;
	wire [15:0] uart_ctrl2_x_speed;
	wire [15:0] uart_ctrl2_y_speed;
	wire [15:0] uart_ctrl2_z_speed;
	wire [31:0] uart_ctrl2_pulse_data;
	wire [1:0] uart_ctrl2_wheel;
	wire [15:0] uart_ctrl2_a_length;
	wire [15:0] uart_ctrl2_b_length;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	wheel_ctrl wheel_ctrl1(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.x_speed(uart_ctrl2_x_speed),
		.y_speed(uart_ctrl2_y_speed),
		.z_speed(uart_ctrl2_z_speed),
		.motor_encoder_A_1(motor_encoder_A_1),
		.motor_encoder_B_1(motor_encoder_B_1),
		.motor_encoder_A_2(motor_encoder_A_2),
		.motor_encoder_B_2(motor_encoder_B_2),
		.motor_encoder_A_3(motor_encoder_A_3),
		.motor_encoder_B_3(motor_encoder_B_3),
		.motor_encoder_A_4(motor_encoder_A_4),
		.motor_encoder_B_4(motor_encoder_B_4),
		.M1_in1(M1_in1),
		.M1_in2(M1_in2),
		.M1_pwm(M1_pwm),
		.M2_in1(M2_in1),
		.M2_in2(M2_in2),
		.M2_pwm(M2_pwm),
		.M3_in1(M3_in1),
		.M3_in2(M3_in2),
		.M3_pwm(M3_pwm),
		.M4_in1(M4_in1),
		.M4_in2(M4_in2),
		.M4_pwm(M4_pwm),
		.wheel(uart_ctrl2_wheel),
		.pulse_data(uart_ctrl2_pulse_data),
		.a_length(uart_ctrl2_a_length),
		.b_length(uart_ctrl2_b_length));

	uart_ctrl uart_ctrl2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.uart_rx(uart_rx),
		.uart_tx(uart_tx),
		.x_speed(uart_ctrl2_x_speed),
		.y_speed(uart_ctrl2_y_speed),
		.z_speed(uart_ctrl2_z_speed),
		.pulse_data(uart_ctrl2_pulse_data),
		.wheel(uart_ctrl2_wheel),
		.a_length(uart_ctrl2_a_length),
		.b_length(uart_ctrl2_b_length),
		.key_in(stop),
		.distance_en(distance_en),
		.direction_en(direction_en),
		.baud_set(baud_set));

endmodule    //motor_chip_top

