module robot_top(
	sys_clk_i,
	sys_rst_n_i,
	uart_rx,
	motor_encoder_A_1,
	motor_encoder_B_1,
	motor_encoder_A_2,
	motor_encoder_B_2,
	motor_encoder_A_3,
	motor_encoder_B_3,
	motor_encoder_A_4,
	motor_encoder_B_4,
	stop,
	dis_rx,
	key_in,
	uart_tx,
	M1_in1,
	M1_in2,
	M1_pwm,
	M2_in1,
	M2_in2,
	M2_pwm,
	M3_in1,
	M3_in2,
	M3_pwm,
	M4_in1,
	M4_in2,
	M4_pwm,
	shcp,
	stcp,
	ds,
	dht11,
	mv_rx,
	steera,
	steerb,
	steerc,
	steerd,
	steere,
	steerf,
	rx_left,
	rx_right);

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input uart_rx;
	input motor_encoder_A_1;
	input motor_encoder_B_1;
	input motor_encoder_A_2;
	input motor_encoder_B_2;
	input motor_encoder_A_3;
	input motor_encoder_B_3;
	input motor_encoder_A_4;
	input motor_encoder_B_4;
	input stop;
	input dis_rx;
	input key_in;
	output uart_tx;
	output M1_in1;
	output M1_in2;
	output M1_pwm;
	output M2_in1;
	output M2_in2;
	output M2_pwm;
	output M3_in1;
	output M3_in2;
	output M3_pwm;
	output M4_in1;
	output M4_in2;
	output M4_pwm;
	output shcp;
	output stcp;
	output ds;
	inout dht11;
	input mv_rx;
	output steera;
	output steerb;
	output steerc;
	output steerd;
	output steere;
	output steerf;
	input rx_left;
	input rx_right;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire uart_rx;
	wire motor_encoder_A_1;
	wire motor_encoder_B_1;
	wire motor_encoder_A_2;
	wire motor_encoder_B_2;
	wire motor_encoder_A_3;
	wire motor_encoder_B_3;
	wire motor_encoder_A_4;
	wire motor_encoder_B_4;
	wire stop;
	wire dis_rx;
	wire key_in;
	wire uart_tx;
	wire M1_in1;
	wire M1_in2;
	wire M1_pwm;
	wire M2_in1;
	wire M2_in2;
	wire M2_pwm;
	wire M3_in1;
	wire M3_in2;
	wire M3_pwm;
	wire M4_in1;
	wire M4_in2;
	wire M4_pwm;
	wire shcp;
	wire stcp;
	wire ds;
	wire dht11;
	wire mv_rx;
	wire steera;
	wire steerb;
	wire steerc;
	wire steerd;
	wire steere;
	wire steerf;
	wire rx_left;
	wire rx_right;
	wire disp_top1_distance_en;
	wire disp_top1_direction_en;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	disp_top disp_top1(
		.clk(sys_clk_i),
		.reset(sys_rst_n_i),
		.rx(dis_rx),
		.shcp(shcp),
		.stcp(stcp),
		.ds(ds),
		.key_in(key_in),
		.dht11(dht11),
		.rx_left(rx_left),
		.rx_right(rx_right),
		.distance_en(disp_top1_distance_en),
		.direction_en(disp_top1_direction_en),
		.rx_ble(uart_rx));

	motor_chip_top motor_chip_top2(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.uart_rx(uart_rx),
		.motor_encoder_A_1(motor_encoder_A_1),
		.motor_encoder_B_1(motor_encoder_B_1),
		.motor_encoder_A_2(motor_encoder_A_2),
		.motor_encoder_B_2(motor_encoder_B_2),
		.motor_encoder_A_3(motor_encoder_A_3),
		.motor_encoder_B_3(motor_encoder_B_3),
		.motor_encoder_A_4(motor_encoder_A_4),
		.motor_encoder_B_4(motor_encoder_B_4),
		.M1_in1(M1_in1),
		.M1_in2(M1_in2),
		.M1_pwm(M1_pwm),
		.M2_in1(M2_in1),
		.M2_in2(M2_in2),
		.M2_pwm(M2_pwm),
		.M3_in1(M3_in1),
		.M3_in2(M3_in2),
		.M3_pwm(M3_pwm),
		.M4_in1(M4_in1),
		.M4_in2(M4_in2),
		.M4_pwm(M4_pwm),
		.uart_tx(uart_tx),
		.stop(stop),
		.distance_en(disp_top1_distance_en),
		.direction_en(disp_top1_direction_en),
		.baud_set( ));

	arm_top arm_top3(
		.sys_clk_i(sys_clk_i),
		.sys_rst_n_i(sys_rst_n_i),
		.mv_rx(mv_rx),
		.ble_rx(uart_rx),
		.steera(steera),
		.steerb(steerb),
		.steerc(steerc),
		.steerd(steerd),
		.steere(steere),
		.steerf(steerf));

endmodule    //robot_top

