#This file is generated by Robei!
#Pin Assignment for Xilinx FPGA with Software Vivado.
set_property PACKAGE_PIN R18 [get_ports rx_ble]
set_property IOSTANDARD LVCMOS33 [get_ports rx_ble]
set_property PACKAGE_PIN N18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W9 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN T10 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN V12 [get_ports rx_left]
set_property IOSTANDARD LVCMOS33 [get_ports rx_left]
set_property PACKAGE_PIN W14 [get_ports rx_right]
set_property IOSTANDARD LVCMOS33 [get_ports rx_right]
set_property PACKAGE_PIN F17 [get_ports key_in]
set_property IOSTANDARD LVCMOS33 [get_ports key_in]
set_property PACKAGE_PIN T20 [get_ports dht11]
set_property IOSTANDARD LVCMOS33 [get_ports dht11]
set_property PACKAGE_PIN V17 [get_ports shcp]
set_property IOSTANDARD LVCMOS33 [get_ports shcp]
set_property PACKAGE_PIN V18 [get_ports stcp]
set_property IOSTANDARD LVCMOS33 [get_ports stcp]
set_property PACKAGE_PIN G15 [get_ports ds]
set_property IOSTANDARD LVCMOS33 [get_ports ds]
set_property PACKAGE_PIN N17 [get_ports distance_en]
set_property IOSTANDARD LVCMOS33 [get_ports distance_en]
set_property PACKAGE_PIN P18 [get_ports direction_en]
set_property IOSTANDARD LVCMOS33 [get_ports direction_en]




