module clk_div(
	sys_clk_i,
	sys_rst_n_i,
	clk_en,
	clk_o);

	//----Parameters:: generated by Robei-----
	parameter P_CLK_DIV_CNT =  1666650;

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input clk_en;
	output clk_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire clk_en;
	wire clk_o;

	//----Code starts here: integrated by Robei-----
	reg                                     r_o_clk_div                ;
	reg                    [31:0]         r_cnt                      ;
	
	assign clk_o = r_o_clk_div;
	
	always @(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if (~sys_rst_n_i) begin
	        r_cnt <= 'd0;
	    end
	    else if (r_cnt == (P_CLK_DIV_CNT >> 1) - 1) begin
	        r_cnt <= 'd0;
	    end
	    else if (clk_en) begin
	        r_cnt <= r_cnt + 1;
	    end
		else
			r_cnt <= r_cnt;
	end
	
	always @(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if (~sys_rst_n_i) begin
	        r_o_clk_div <= 'd0;
	    end
	    else if (r_cnt == (P_CLK_DIV_CNT >> 1) - 1) begin
	        r_o_clk_div <= ~ r_o_clk_div;
	    end
	    else begin
	        r_o_clk_div <= r_o_clk_div;
	    end
	end
	
endmodule    //clk_div

