module distance(
	clk,
	reset,
	uart_rx,
	dist,
	dist_po_flag,
	dist_reg);

	//---Ports declearation: generated by Robei---
	input clk;
	input reset;
	input uart_rx;
	output [15:0] dist;
	output dist_po_flag;
	output [15:0] dist_reg;

	wire clk;
	wire reset;
	wire uart_rx;
	wire [15:0] dist;
	reg dist_po_flag;
	reg [15:0] dist_reg;

	//----Code starts here: integrated by Robei-----
	/*
	        ATK-MS53L1M 模块--Normal 模式、Modbus 模式、IIC 模式
	        传输格式为
	        d:<space>xxx mm
	        40mm~3900mm（无光学镜片可达 4000mm）
	        需要借助ATK-TOF上位机对参数进行配置
	        如：设备ID/工作模式/波特率/回传速率/测量模式/校准 等
	        此代码应该配置成Normal模式 Modbus模式需要报文发送等 IIC模式需要自己查阅手册 实现起来较为麻烦
	        四个字节 -- 4000--应该是ASCII码值接收
	        实现'd';':'字符串检测
	    */
	//字符串检测--状态机参数 parameter define
	//检测d和:
	parameter CHECK_d = 2'b01,
	CHECK_maohao = 2'b10;
	//reg define
	reg [1:0]state;
	reg work_en;
	reg [2:0]rx_cnt;
	reg [31:0]rx_4byte_data;//接收过程4字节数据寄存器
	reg [31:0]uart_4byte_data;
	reg dist_po_flag_reg;
	wire [7:0]po_data;
	wire po_flag;
	always@(posedge clk or negedge reset)
	if(reset == 0)
	    state <= CHECK_d;
	else begin
	    case(state)
	        CHECK_d:
	            begin
	            if(po_flag == 1'b1 && po_data == "d") 
	            state <= CHECK_maohao;
	            else
	            state <= CHECK_d;
	            end
	
	        CHECK_maohao:
	            if(po_flag && po_data == ":") 
	            state <= CHECK_d;
	            else if(po_flag && po_data != ":")
	            state <= CHECK_d;
	            else
	            state <= CHECK_maohao;
	        default:state <= CHECK_d;
	    endcase		
	end
	//work_en
	always@(posedge clk or negedge reset)
	if(reset == 0)
	    work_en <= 0;
	else if(rx_cnt == 'd4)
	    work_en <= 0;
	else if(state == CHECK_maohao && (po_flag && po_data == ":"))
	    work_en <= 1;
	else
	    work_en <= work_en;
	//rx_cnt
	always@(posedge clk or negedge reset)
	if(reset == 0)
	    rx_cnt <= 3'd0;
	else if(work_en)begin
	    if(po_flag == 1'b1)begin
	        rx_cnt <= rx_cnt + 1'b1;
	    end
	    else 
	        rx_cnt <= rx_cnt;
	end
	else
	    rx_cnt <= 3'd0;
	//rx_4byte_data
	always@(posedge clk or negedge reset)
	if(reset == 0)
	    rx_4byte_data <= 'd0;
	else if((work_en == 1'b1)&&(po_flag == 1'b1))
	    rx_4byte_data <= {rx_4byte_data[23:0], po_data}; 
	else
	    rx_4byte_data <= rx_4byte_data;
	//uart_4byte_data
	//接收到4字节数据后，从寄存器中取出数据
	always @(posedge clk or negedge reset) 
	if (reset == 0) 
	    uart_4byte_data <= 1'd0;
	else if((rx_cnt == 4)&&(work_en == 1'b1))
	begin
	    uart_4byte_data <= rx_4byte_data;
	end		  
	else
	    uart_4byte_data <= uart_4byte_data;
	//dist_po_flag
	always@(posedge clk or negedge reset)
	if(reset == 0)
	   dist_po_flag <= 0;
	else if((rx_cnt == 4)&&(work_en == 1'b1))
	   dist_po_flag <= 1;
	else
	   dist_po_flag <= 0;
	
	always@(posedge clk or negedge reset)
	if(reset == 0)
	   dist_po_flag_reg <= 0;
	else 
	   dist_po_flag_reg <= dist_po_flag;
	//reg [15:0] dist_reg;
	//减去48因为十进制数48对应的是'0'
	always@(posedge clk or negedge reset)
	if(reset == 0)
	  dist_reg <= 0;
	else if((rx_cnt == 4)&&(work_en == 1'b1)||(dist_po_flag == 1'b1))begin
	    if(uart_4byte_data[7:0] == " ")
	         dist_reg <= 0;
	    else if((uart_4byte_data[15:8])==" ")
	        dist_reg <= uart_4byte_data[7:0]-'d48;
	    else if((uart_4byte_data[23:16])==" ")
	        dist_reg <= (uart_4byte_data[15:8]-48)*10 + (uart_4byte_data[7:0]-48);
	    else if((uart_4byte_data[31:24])==" ")begin
	        dist_reg <= (uart_4byte_data[23:16]-48)*100 + (uart_4byte_data[15:8]-48)*10 + (uart_4byte_data[7:0]-48);
	    end
	    else  begin
	     dist_reg <= (uart_4byte_data[31:24]-48)*1000 + (uart_4byte_data[23:16]-48)*100 + (uart_4byte_data[15:8]-48)*10 + (uart_4byte_data[7:0]-48);
	    end
	end
	
	wire [3:0]data_3;
	wire [3:0]data_2;
	wire [3:0]data_1;
	wire [3:0]data_0;
	assign data_3 = dist_reg/1000;
	assign data_2 = dist_reg%1000/100;
	assign data_1 = dist_reg%1000%100/10;
	assign data_0 = dist_reg%1000%100%10;
	
	assign dist = {data_3,data_2,data_1,data_0}; 
	
	//---Module instantiation---
	uart_rx #( 'd289) uart_rx1(
		.clk(clk),
		.reset(reset),
		.rx(uart_rx),
		.po_data(po_data),
		.po_flag(po_flag));

endmodule    //distance

