module switch_key_filter(
	clk,
	reset,
	key_in,
	key_flag);

	//---Ports declearation: generated by Robei---
	input clk;
	input reset;
	input key_in;
	output key_flag;

	wire clk;
	wire reset;
	wire key_in;
	reg key_flag;

	//----Code starts here: integrated by Robei-----
	reg [19:0]cnt_20ms;
	 
	always@(posedge clk or negedge reset)
	if(reset == 0)
	  cnt_20ms <= 0;
	else if(key_in == 1)
	  cnt_20ms <= 1;
	else begin
	  if(cnt_20ms < 999_999)
			cnt_20ms <= cnt_20ms + 1;
	  else
	  cnt_20ms <= 999_999;
	end
	 
	always@(posedge clk or negedge reset)
	if(reset == 0)
	  key_flag <=0;
	else if(cnt_20ms == 999_998)
	  key_flag <= 1;
	else
	  key_flag <= 0;
endmodule    //switch_key_filter

