module timer(
	sys_clk_i,
	sys_rst_n_i,
	timer_cnt_en_i,
	timer_cnt_clr_i,
	timer_ack_o);

	//----Parameters:: generated by Robei-----
	parameter encoder_sys_cycle = 8'd30;
	parameter  encoder_inspection_cycle = 20'd16_665;

	//---Ports declearation: generated by Robei---
	input sys_clk_i;
	input sys_rst_n_i;
	input timer_cnt_en_i;
	input timer_cnt_clr_i;
	output timer_ack_o;

	wire sys_clk_i;
	wire sys_rst_n_i;
	wire timer_cnt_en_i;
	wire timer_cnt_clr_i;
	wire timer_ack_o;

	//----Code starts here: integrated by Robei-----
	reg[31:0]   time_cnt;
	
	assign timer_ack_o = ( time_cnt == encoder_inspection_cycle) ? 1'b1 : 1'b0;
	
	always @(posedge sys_clk_i or negedge sys_rst_n_i) begin
	    if( sys_rst_n_i == 1'b0)
	        time_cnt <= 32'd0;
	    else if( time_cnt == encoder_inspection_cycle || timer_cnt_clr_i ==  1'b1)
	        time_cnt <= 32'd0;
	    else if( timer_cnt_en_i == 1'b1 )
	        time_cnt <= time_cnt + 1'b1;
	    else
	        time_cnt <= time_cnt;
	end
endmodule    //timer

